### ISSUE TITLE
Hoe werkt de app: Verbeterpunten en vragen over tijdsduur en afstand 

### ISSUE THREAD

**Issue by JoshuaLuckers** [minvws/nl-covid19-notification-app-website#103]
Bestand: https://github.com/minvws/nl-covid19-notification-app-website/blob/65dbb9ef387d772a8118d339d1e357fae63bccea/_statements/nl/2-how-does-it-work.md

In de samenvatting en uitleg staat `enige tijd in de buurt` (regel 5 en 9) terwijl onder het kopje "Wanneer krijg ik een melding?" gesproken wordt over `langere tijd dichtbij` (regel 28). 
Spreek dit elkaar niet tegen?

Verder zou het ook goed zijn om meer duidelijkheid te geven over de tijdsduur en afstand waaraan mensen moeten denken. 
- Enige en/of langer tijd is dat 5 minuten, 30 minuten?
- In de buurt/dichtbij is dat 1,5 meter, 5 meter?

**Comment by markmarijnissen** [comment]
Bluetooth signaalsterkte (RSSI) is sterk afhankelijk van de omgeving, waarbij reflectoren (b.v. spiegels of metaal) het signaal verzwakken maar muren bijvoorbeeld helemaal niet. 

Zo kun je een fout-positief signaal krijgen van de buurvrouw (door de muur heen), of een fout-negatief signaal als je samen in de trein zit met een ongelukkige positie. 

Dus naast de technische verificatie (dat de app foutloos werkt), hoe valideer je de claim dat BLE RSSI iets zegt over de afstand? En hoe ga je om met fouten?

Dat zou ik graag willen weten!

**Comment by dirkx** [comment]
Misschien handig om even naar de laatste kamerbrieven te kijken - hiervoor zijn uitgebreide veld en lab proeven gedaan, calibratie bepaald. De (meest recente) rapporten zitten bij de dinsdag-kamerbrieven.

**Comment by JoshuaLuckers** [comment]
Ik heb deze issue voornamelijk gemaakt omdat de website hier, mijn inziens, geen duidelijkheid over geeft.

**Comment by markmarijnissen** [comment]
Bedankt voor het inhoudelijke antwoord @dirkx. 

Ik wil graag, net als @JoshuaLuckers, even de aandacht verleggen van de inhoud naar de website. Ik denk dat het belangrijk is om dit goed uit te leggen. Net zoals privacy kan nauwkeurigheid namelijk een drempel voor gebruikers zijn om de app te gebruiken. (Althans, voor mij is het een drempel en ik weet die kamerbrieven niet te vinden. Daar moet ik dus bij geholpen worden!)

Je zou als kopje kunnen toevoegen: "Hoe nauwkeurig is de app?"

Daarnaast lijkt het mij goed om de termen expliciet te maken: "enige tijd" > "15 minuten". 

Bij "dicht bij elkaar" wordt het inderdaad lastig dit precies te maken, maar dat leent zich juist voor een voetnoot of sterretje (*) waarin de nuance wordt uitgelegd.

**Comment by anneke** [comment]
Reactie van onze content manager:

@markmarijnissen schreef:
_Je zou als kopje kunnen toevoegen: 'Hoe nauwkeurig is de app?'__ 

Die vraag wordt op dit moment weinig gesteld via de helpdesk (mail, telefoon) en via de kanalen van webcare. We gaan er voor zorgen dat dit zeker toegevoegd wordt aan 'minder gestelde vragen’.

@markmarijnissen schreef:
_Daarnaast lijkt het mij goed om de termen expliciet te maken: 'enige tijd' > ’15 minuten'.
Bij 'dicht bij elkaar’ wordt het inderdaad lastig dit precies te maken, maar dat leent zich juist voor een voetnoot of sterretje (*) waarin de nuance wordt uitgelegd."_

Hier geldt hetzelfde voor, we gaan deze suggestie meenemen!

**Comment by EdoPlantinga** [comment]
@markmarijnissen @JoshuaLuckers Dank voor de suggesties. Dit komt naar voren in de explainer video's die we bij landelijke lancering zullen toevoegen. Voor nu sluit ik ze.
