### ISSUE TITLE
[summer of  2020]: [VWS/Covid19NotificationApp] Broken

### ISSUE THREAD

**Issue by msduketown** [minvws/nl-covid19-notification-app-website#111]
### Describe the bug, issue or concern

This app has too many unsafe dependencies and is managed by a digibeet. Also a scary license without ethics or accountibility, which is a feature, not a bug.

E.g. 

### To Reproduce
you don't want to clone this behaviour, trust me.

### Expected behavior
yes, history repeats itself; nowadays even in digital form

### Screenshots
look around you

**Desktop (please complete the following information):**
All OS'es are in court and UserSpace is afraid to type.

**Smartphone (please complete the following information):**
 smartwatch, smartthing.. before you know IT, you'll start talking brands, but that is later in Court.

### Additional context
#2FA #5GTerror #1984 #kafka

### Governance attemp
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by msduketown** [comment]
Yeah, WHO started this? Who gave first commit rights? And what about these cookies?

**Comment by AnouschkaScholten** [comment]
Thank you for your submission. The discussions about the integrity of the app are very important and we discuss these in the Code for NL Slack. We invite you to post your concerns there: https://minvws.github.io/nl-covid19-notification-app-community-website/#/blocks/discuss
