### ISSUE TITLE
Inschakelen Subresource Integrity op externe bronnen

### ISSUE THREAD

**Issue by NL-William** [minvws/nl-covid19-notification-app-website#116]
In https://coronamelder.nl/js/piwik.js?v= wordt een externe bron ingeladen van statistiek.rijksoverheid.nl/piwik/.
Bij externe javascript bronnen wil je vooral voorkomen dat deze invloed kunnen uitoefenen, anders dan gewenst, op de site.
Dit kan door het gebruik van een integrity hash op de bron.

In dit geval zou een kwaadwillende die slechts toegang weet te krijgen tot statistiek.rijksoverheid.nl ook de coronamelder.nl site kunnen manipuleren. Met SRI actief is dat onmogelijk, omdat de hash dan niet matched en moderne browsers weigeren de bron te laten.

Het lijkt daarom verstandig Subresource Integrity in te schakelen op deze bronnen, zie https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity.

Let wel: bij een update van piwiki.js zal de hash wel opnieuw moeten worden geladen, het is dus verstandig afspraken te maken over versiebeheer en updates.

**Comment by StommePoes** [comment]
wij willen niet nog een BrowseAloud situatie
https://www.theregister.com/2018/02/11/browsealoud_compromised_coinhive/

**Comment by bwbroersma** [comment]
Good catch, [the pentest](https://www.rijksoverheid.nl/onderwerpen/coronavirus-app/documenten/rapporten/2020/07/15/testrapport-penetratietest-coronamelder) mentions using CSP hashes, instead of CRI, both can achieve the same effect, however external hashes are not yet fully supported since it's only since CSP 3.0, so I should go with SRI.
I already mentioned this in the other website project https://github.com/minvws/nl-covid19-notification-app-community-website/issues/5#issuecomment-643463985:
> You can easily generate SRI, if you trust the file, see the [SRI hash generator](https://www.srihash.org/).
> 
> ```shell
> curl -sSfqA '' --compressed 'https://nl-design-system.gitlab.io/nl-design-system/uno/core/uno.css' \
>  | openssl dgst -sha256 -binary \
>  | openssl base64 -A
> # TcpPsVA7aFeDShDs6vennop1pZ/5CoLg1UxX+Y6xMrI=
> ```
> 
> so the HTML should be
> 
> ```
> <link
>     href="https://nl-design-system.gitlab.io/nl-design-system/uno/core/uno.css"
>     rel="stylesheet"
>     integrity="sha256-TcpPsVA7aFeDShDs6vennop1pZ/5CoLg1UxX+Y6xMrI="
>     crossorigin="anonymous">
> ```
> 
> But you _only_ want to do this with URLs that will not update the content, so `Cache-Control: immutable` or the promise of it being immutable.

**Comment by NL-William** [comment]
In a perfect world you would combine SRI and CSP like this:

```
<script
    src="https://coronamelder.nl/js/piwik.js?v=xyz"
    integrity="<sha256-base64-from-content-hash>"
    crossorigin="anonymous"
   nonce="<random-sha64-base64-from-CSP>"
>
```

Where the `integrity` is immutable (linked to the source hash), and the `[nonce]` changes on every page request (linked to the CSP hash, [more info on nonces here](https://content-security-policy.com/nonce/).

**Comment by ph00lt0** [comment]
@NL-William I don't think that is a huge concern as Microsoft pushes everyone into there new versions either way. The old version of Edge also is removed in last versions of windows. The only problem could be enterprise systems that do not automatically update to newer versions on windows (and also miss out on security updates).

**Comment by gberkouwer** [comment]
Dit issue kan simpel gesloten worden omdat Piwik is verwijderd van de website.
