### ISSUE TITLE
Website hosting op groene stroom zetten

### ISSUE THREAD

**Issue by NL-William** [minvws/nl-covid19-notification-app-website#117]
Volgens https://www.thegreenwebfoundation.org/green-web-check/?url=coronamelder.nl is de website momenteel gehost op grijze stroom. 

Dit kan twee dingen betekenen:
 * De hoster gebruikt inderdaad grijze stroom: contractueel repareren dat dit groene stroom moet zijn
 * De hoster heeft zijn groene stroomgebruik niet gemeld bij The Green Web Foundation

**Comment by AnouschkaScholten** [comment]
We leggen dit voor aan de hosting partij.

**Comment by anneke** [comment]
We zijn over naar Freedom Internet als hostingpartij! Wij zijn aan het verifieren of dit ook dit issue oplost 😄

**Comment by anneke** [comment]
Excuses voor de late reactie, maar dit is geverifieerd! Bedankt @NL-William
