### ISSUE TITLE
Plaatsen van een /.well-known/security.txt

### ISSUE THREAD

**Issue by NL-William** [minvws/nl-covid19-notification-app-website#118]
Er is een responsible disclosure policy actief op de site (zoals staat op https://coronamelder.nl/kwetsbaarheid-melden), maar https://coronamelder.nl/.well-known/security.txt ontbreekt (wat de plek is waar Ethische Hackers als eerste kijken).

Op https://securitytxt.org is deze voor het gemak te genereren.

**Comment by hugopilot** [comment]
https://github.com/minvws/nl-covid19-notification-app-backend/issues/8#issuecomment-678642414

**Comment by anneke** [comment]
Bedankt voor de tip! Thanks for the advice. Turns out, I thought this was going to be more work than it was. I've added a `security.txt` in a `.well-known` folder and in the root (to be sure). Thanks to Gerrit Berkouwer for being so patient and reminding me! 
This will be added in the next release on friday the 13th.

**Comment by gberkouwer** [comment]
Het bestand is blijkbaar nog niet gelukt in de /well-known directory? Hij staat wel in de root.

**Comment by showengineer** [comment]
> Het bestand is blijkbaar nog niet gelukt in de /well-known directory? Hij staat wel in de root.

Can confirm dat het nog niet te bereiken is via `https://coronamelder.nl/.well-known/security.txt`.

De nieuwste versie van de security.txt standaard verplicht ook een `Expires` field, maar ik laat aan jullie de keuze om dat erbij te zetten.

**Comment by anneke** [comment]
Er staat een expires bij en de URL is aangepast, maar het lijkt er op dat de server mensen leidt naar de 404 pagina voor iets anders. Heb jij een idee @mellewynia ? :)

**Comment by anneke** [comment]
Het is gelukt om de link te corrigeren! Hij is nu bereikbaar. Inclusief `expires`! Bedankt allemaal.
