### ISSUE TITLE
Securityheaders ook op het www subdomein zetten

### ISSUE THREAD

**Issue by gberkouwer** [minvws/nl-covid19-notification-app-website#120]
De securityheaders zijn gezet op het kale domein coronamelder.nl. Het is verstandig dit ook door te voeren voor het www-subdomein.

**Comment by bwbroersma** [comment]
Ik zou nog steeds voor de `www.`-variant gaan voor de hoofd website :wink:, ik blijf het raar vinden [dat daar vanaf is geweken](https://github.com/minvws/nl-covid19-notification-app-website/issues/45#issuecomment-653594403) door een foutje.
