### ISSUE TITLE
E-mail standaarden ook volledig toepassen voor www.coronamelder.nl 

### ISSUE THREAD

**Issue by gberkouwer** [minvws/nl-covid19-notification-app-website#121]
De e-mail standaarden zoals te testen via Internet.nl zijn voor het kale domein coronamelder.nl volledig ingesteld, met een score van 100%. Het is verstandig dit ook te doen voor www.coronamelder.nl, nu een score van 80%.

**Comment by NL-William** [comment]
Het is tevens verstandig om op *.coronamelder.nl (de subdomeinen die niet expliciet zijn ingericht met een A record) SPF in te regelen. 

e.g. *.coronamelder.nl.  IN TXT "v=spf1 –all"

Voorbeeldimplementatie: https://internet.nl/mail/coronamelder-demo.internet.nl/392268/ :)

Zo zijn ook eventueel te verzinnen subdomeinen (bv. @download.coronamelder.nl) meteen geblokkeerd voor misbruik.

**Comment by gberkouwer** [comment]
Zeker, goed punt!

**Comment by anneke** [comment]
Deze staat inmiddels op 100%!

https://internet.nl/mail/www.coronamelder.nl/434101/

Alleen de subdomeinen nog niet. Ik ga hier achteraan!
