### ISSUE TITLE
Cookies tracking eruit halen!

### ISSUE THREAD

**Issue by AnouschkaScholten** [minvws/nl-covid19-notification-app-website#127]

**Comment by mellewynia** [comment]
Even ter info van dit draadje, er is inmiddels een update: 
https://github.com/minvws/nl-covid19-notification-app-website/pull/130

**Comment by ph00lt0** [comment]
Ik neem aan dat dit wegmoest moest omdat ze data bij Amazon opslaan in de U.S. en de ontwikkelingen rondom het EU-US privacyshield. Wellicht kan de overheid dan alsnog een self-hosted matomo installatie overwegen. 
https://matomo.org/

Eerder hier voorgesteld: [#57 ](https://github.com/minvws/nl-covid19-notification-app-website/issues/57)

**Comment by mellewynia** [comment]
Dit ticket is in principe afgerond met update: feature/2020-07-31-update
