### ISSUE TITLE
Use WOFF2 format instead of WOFF

### ISSUE THREAD

**Issue by gberkouwer** [minvws/nl-covid19-notification-app-website#141]
Is there a reason to use WOFF for fonts? Why not use the WOFF2 version of the fonts? Smaller (30% gain maybe?), modern. Maybe make a fallback to WOFF for IE11.

**Comment by anneke** [comment]
Hi Gerrit, I've opened a pull-request with the WOFF2 version (and WOFF fallback). I am a little concerned about a negative impact on performance though, as I'm not entirely sure that it is not now loading the WOFF2 *and* WOFF files. I will probably have another look at this this week to check this. @mellewynia

**Comment by gberkouwer** [comment]
Hi @anneke , great that you pick this up :-). Offcourse only load woff as a fallback when woff2 does not work for the user-agent, most important one being IE11. I am not a frontend dev so cannot help you with the solution, but loading both should be a no-go :-).

**Comment by anneke** [comment]
Hi @gberkouwer , I struggled a little with getting my commits verified, but the pull-request is now open and waiting for feedback correctly here: https://github.com/minvws/nl-covid19-notification-app-website/pull/183 
I will keep you posted :)

**Comment by gberkouwer** [comment]
Great work! :-)
