### ISSUE TITLE
Slider: bullets zijn links met button semantics

### ISSUE THREAD

**Issue by hidde** [minvws/nl-covid19-notification-app-website#177]
In de slider zijn de ’bullets’ opgemaakt als links, met `role="button"` en `tabindex="0"`. Dit overtreedt de [Second rule of ARIA](https://www.w3.org/TR/using-aria/#second): we overschrijven de ingebouwde semantics.

Laten we hier kiezen voor ofwel `button`s, ofwel `a`s (zonder `role="button"` en zonder `tabindex="0"`, want die voegen niets toe). Momenteel werken (en bestaan) ze niet zonder JavaScript, dus ik zou neigen naar `button`s.   

Gerelateerd: de vorige/volgende buttons hebben een `role="button"`, die is niet nodig, want `button` is de default `role` van buttons.

**Comment by anneke** [comment]
Ik heb hier in een PR buttons van gemaakt, en een aanpassing gedaan zodat er geen role="button" meer op komt (en in ons geval ook geen aria-label, want we hebben al een span met de tekst binnen de buttons). (Keuze voor buttons naar aanleiding van een issue van Jules Ernst). Thanks Hidde!

**Comment by anneke** [comment]
Helaas lukt het me niet om van die tabindex af te komen, maar is die schadelijk als die op 0 staat?

**Comment by hidde** [comment]
Die tabindex is inderdaad geen probleem voor gebruikers, zolang het geen positief getal is (dus `0` of `-1`)
