### ISSUE TITLE
Links in de footer  (RIVM en GGD) werken niet

### ISSUE THREAD

**Issue by hidde** [minvws/nl-covid19-notification-app-website#189]

**Comment by anneke** [comment]
@mikecodo zit hier overlap in met https://github.com/minvws/nl-covid19-notification-app-website/issues/239 ? Want daar staat een PR voor klaar.

**Comment by mikecodo** [comment]
@anneke Er zit overlap in. De issue ging over dat de links er niet in stonden. Ze zijn toegevoegd alleen een verkeerde link voor de Engelse taal. De fix zit in de pr van #239

**Comment by anneke** [comment]
Okee, dan sluit ik deze issue
