### ISSUE TITLE
Alleen apple badge tonen op ios en play store bij android

### ISSUE THREAD

**Issue by mikecodo** [minvws/nl-covid19-notification-app-website#225]

**Comment by SleeplessByte** [comment]
Er zullen genoeg mensen zijn die de app op een Android telefoon willen installeren terwijl ze op een iOS device browsen of vice versa (denk aan familie/werk/meerdere telefoons). 

Is het niet een beter idee om alle knoppen wel altijd weer te geven, of in ieder geval bereikbaar te maken? Veel andere websites selecteren je huidige systeem voor, maar laten de rest nog wel toe.
