### ISSUE TITLE
De build stap neemt te veel files mee

### ISSUE THREAD

**Issue by matijs** [minvws/nl-covid19-notification-app-website#228]
Files zoals de README.md (https://coronamelder.nl/README.md) en Gemfile_ (https://coronamelder.nl/Gemfile_) komen op de live site terecht.

**Comment by arianvp** [comment]
je kunt files excluden in `_config.yml`.



Zie voorbeeld van de community website: 

```yaml
exclude:
  - nix
  - gemset.nix
  - default.nix
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSES.md
  - LICENSE.txt
  - LICENSE.pdf
```

https://github.com/minvws/nl-covid19-notification-app-community-website/blob/master/_config.yml

**Comment by anneke** [comment]
Bedankt @arianvp , ik heb een PR geopend!
