### ISSUE TITLE
Verbeterpunt antwoord 'Wanneer krijg ik een melding van de app'

### ISSUE THREAD

**Issue by ehotting** [minvws/nl-covid19-notification-app-website#229]
In het antwoord zou ik ook verwachten dat iets wordt gezegd over hoe lang de app terugkijkt voor het maken van matches. Dat is 14 dagen.

Overigens is die 14 dagen ook relevant voor alle mensen die nu zeggen 'voor mij is de app niet relevant want ik woon niet in het gebied waar getest wordt', immers wanneer alle GGD's meewerken hebben die mensen al 14 dagen nuttige historie opgebouwd als ze de  app nu installeren

**Comment by anneke** [comment]
Beste Eelco, bedankt voor je feedback! We gaan dit voorleggen aan de content manager.

**Comment by anneke** [comment]
We moeten dit uitzoeken, maar we kunnen nu al zeggen dat we deze vraag zullen gaan beantwoorden op een pagina met zogenaamde ‘minder gestelde vragen’ die ontwikkeld wordt. Daar komen veel meer antwoorden met meer inhoud, ook wat betreft technische vragen. De basisinformatie en de FAQs blijven dus gericht op de grote lijnen.

**Comment by EdoPlantinga** [comment]
Deze vraag wordt ook beantwoord in een van de filmpjes die zijn gemaakt. Ik sluit deze hier.
