### ISSUE TITLE
Verbeterpunt antwoord 'Wat betekent het als  je een melding krijgt?'

### ISSUE THREAD

**Issue by ehotting** [minvws/nl-covid19-notification-app-website#230]
Nergens in het antwoord staat wat gebeurt wanneer je dagelijks in de buurt bent geweest van iemand die later corona blijkt te hebben. Krijg je dan een melding over de dag van eerste contactmoment, de dag van laatste contactmoment, een willekeurige dag uit die periode of een overzicht van alle dagen?

Let wel, dit is ook relevant om te bepalen hoe lang je in thuisquarantaine zou moeten gaan. Als het 13 dagen geleden was is dat iets heel anders dan 'vanaf 13 dagen geleden elke dag tot nu toe'. De app moet daar  heldere over zijn zodat mensen kunnen rekenen met de info die ze krijgen.

**Comment by anneke** [comment]
Hoi Eelco! We gaan ook deze feedback voorleggen aan de content manager.

**Comment by anneke** [comment]
Dit is onderdeel van het reguliere BCO van de GGD. Mensen die dagelijks met een besmet persoon in contact zijn geweest worden so wie so gebeld. We pakken dit op met de mensen die die FAQs schrijven!

**Comment by EdoPlantinga** [comment]
Ik heb deze gesloten. Het is m.i. te gedetailleerd voor op de website. De kans dat je meerdere keren contact hebt gehad met iemand én dat je niet weet wie dat was (via regulier BCO), is gering. Dit omschrijven roept meer vragen op dan dat het antwoorden geeft.
