### ISSUE TITLE
Url naar government.nl in footer verwijst naar rijksoverheid.nl

### ISSUE THREAD

**Issue by rohitjethoe** [minvws/nl-covid19-notification-app-website#239]
## Url naar government.nl in footer verwijst naar rijksoverheid.nl

In de footer onder meer informatie staat een link naar de website van de rijksoverheid. Als je de website van de coronamelder app in het Engels bekijkt zie je i.p.v. `rijksoverheid.nl` `government.nl` staan. Deze link verwijst nogsteeds naar `rijksoverheid.nl` i.p.v. `government.nl`.

### Screenshot van het probleem
<img width="1162" alt="screenshot" src="https://user-images.githubusercontent.com/69147709/90403960-00257500-e0a2-11ea-969e-3e562082d5ac.png">

**Comment by rohitjethoe** [comment]
Ik kan deze issue ook gelijk aanpakken in de PR (#232) die ik al eerder had gemaakt.

**Comment by anneke** [comment]
Bedankt Rohit! Top 👍  Zoals gezegd kijk ik vandaag naar je PR.

**Comment by anneke** [comment]
De PR waarin dit opgelost wordt heb ik goedgekeurd, maar het is aan het kern development team om deze te mergen!
