### ISSUE TITLE
Homepagina bevat lege `<h2>`

### ISSUE THREAD

**Issue by hidde** [minvws/nl-covid19-notification-app-website#247]
Op de homepage staat een lege `<h2>`. Omdat headings door sommige gebruikers als navigatie worden gebruikt (zie [Headings are tables of contents](https://hiddedevries.nl/en/blog/2018-09-01-heading-structures-are-tables-of-contents)), kan dit in de weg zitten.

Oplossing: lege `<h2>` verwijderen. (Mocht er later een kop op die plek en op dat niveau nodig zijn, kan dit dan worden toegevoegd)

**Comment by anneke** [comment]
Ik heb een PR geopend om dit op te lossen, al is het volgens mij niet ideaal om voor een subtitel een h2 te gebruiken daar? In ieder geval staat er iets klaar om het lege element weg te laten als er geen tekst voor is.

**Comment by hidde** [comment]
Heel goed punt. Het hangt van de content af, maar kans is groot dat dit in de meeste gevallen best een `<p>` kan zijn, want niet echt nuttig bijdraagt aan headingstructuur. Misschien in deze PR ook gelijk aanpassen?
