### ISSUE TITLE
Slider: sommige knopteksten niet in juiste taal

### ISSUE THREAD

**Issue by hidde** [minvws/nl-covid19-notification-app-website#249]
In de slider hebben sommige knoppen teksten in het Engels, terwijl de taal op ”Nederlands” staat.

Oplossing: lokaliseer de teksten*, zorg dat ze in de huidige taal beschikbaar zijn. Let op: er zitten op deze knoppen wel Nederlandse teksten in de broncode, maar die worden overgeschreven met `aria-label` op de knop.

*Overzicht teksten waar dit misgaat: 

- button “Previous slide”
- button “Previous slide”
- link “Go to slide [x]”

**Comment by anneke** [comment]
Ik heb hier naar gekeken, maar ik kan helaas niet zo 1, 2, 3, zelf een voorstel doen in een pull-request. 

Voor meer achtergrond is hier een link naar de API van de slider:
https://github.com/nolimits4web/swiper/blob/Swiper5/API.md#accessibility-a11y

Het lijkt er mij op dat we de waardes van prevSlideMessage, nextSlideMessage en paginationBulletMessage (`Go to slide {{index}}'`) willen overschrijven per taal.

**Comment by anneke** [comment]
Ik heb hier nog even naar gekeken en ik heb hier een fix voor meegenomen in PR #268. Het verdient geen schoonheidsprijs, maar ik hoop de makers van Swiper nu goede feedback te kunnen geven om een en ander beter mogelijk te maken in hun API.

**Comment by anneke** [comment]
Heb een PR geopend voor een verbetering aan Swiper voor mensen die net als wij tegen dit issue kunnen aanlopen https://github.com/nolimits4web/swiper/pull/3774

**Comment by anneke** [comment]
We hebben hier schreden in gezet, maar zouden een CSP policy moeten aanpassen voor de oplossing die we hebben bedacht. Omdat we hoogstwaarschijnlijk afscheid nemen van de slider komende week sluit ik deze issue voor nu. Mocht het terugkomen, dan gaan we hier verder mee aan de slag!
