### ISSUE TITLE
Typo in Privacyverklaring

### ISSUE THREAD

**Issue by NL-William** [minvws/nl-covid19-notification-app-website#251]
In de privacyverklaring https://coronamelder.nl/nl/privacy-in-app staat een typo onder "6. Aan wie worden persoonsgegevens verstrekt?"

**HeHet** uitzenden en ontvangen van de RPIs gebeurt lokaal op de smartphones. Als een besmetting is vastgesteld kan de gebruiker ervoor kiezen zijn of haar TEKs, tezamen met een unieke autorisatiecode, naar de centrale server te sturen. De centrale server wordt beheerd door het CIBG met KPN als onderaannemer (verwerker). 

Correctie:
***Het*** uitzenden.

**Comment by rdeveen** [comment]
https://github.com/minvws/nl-covid19-notification-app-website/pull/275 en https://github.com/minvws/nl-covid19-notification-app-website/pull/274
