### ISSUE TITLE
Slider: Onderstreepte tekst / niet klikbaar

### ISSUE THREAD

**Issue by julezrulez** [minvws/nl-covid19-notification-app-website#255]
In de slider wordt onderstreepte tekst gebruikt wat lijkt alsof je erop kan klikken (hyperlink). Maar de tekst is niet klikbaar.
![image](https://user-images.githubusercontent.com/8790904/90692838-1d12a180-e276-11ea-9221-c0c95751557d.png)

D'r is hier iets kapot gegaan in de oorspronkelijke css. HTML-code lijkt namelijk niet veranderd.

**Comment by hidde** [comment]
@anneke ontwerp terugdraaien naar wat het was zou dit probleem oplossen.

**Comment by anneke** [comment]
👍 ik weet niet wat het ontwerp was, maar fijn om te weten welke richting we kunnen opgaan hiermee!

**Comment by anneke** [comment]
In het nieuwe ontwerp van de homepage (die naar verwachting komende week live gaat) wordt de slider vervangen waardoor dit geen issue meer zou moeten zijn! Mocht dit veranderen, heropen ik deze issue.
