### ISSUE TITLE
Textual issue in accessibility statement (NL)

### ISSUE THREAD

**Issue by jorisleker** [minvws/nl-covid19-notification-app-website#262]
Reported by @herkocoomans via https://github.com/minvws/nl-covid19-notification-app-design/issues/88

Feedback concerning https://coronamelder.nl/nl/toegankelijkheidsverklaring

> Hoe we zorgen voor een toegankelijke CoronaMelder?

The title of this section is gramatically incorrect. I suggest 'Hoe zorgen we voor een toegankelijke CoronaMelder app?'

Second bullet: 
> In het ontwerp van de app is rekening gehouden met toegankelijkheid. Zo is waar een tekstalternatief voor afbeeldingen gebruikt en is er gelet op het gebruik van kleur en kleurcontrast' is gramatically incorrect.

I suggest 'In het ontwerp van de app is rekening gehouden met toegankelijkheid. Zo is overal een tekstalternatief voor afbeeldingen beschikbaar en is er gelet op het correcte gebruik van kleur en kleurcontrast'

Fourth bullet:
> De toegankelijkhied van de app is zowel door het team als een onafhankelijke partij getest'. 

I suggest adding a link to the test results of the independant third party.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by anneke** [comment]
Hoi, goede toevoegingen, maar er komen nog nieuwe teksten aan! Daarom sluit ik deze issue voor nu.
