### ISSUE TITLE
A11Y issues to solve

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-website#27]
See #25 comments.
- [ ] `<label><hX>` :arrow_right: `<hX><label>` :heavy_plus_sign: CSS switch
- [ ] `<header><h1>` :arrow_right: `<header><h1 aria-hidden="true">` :heavy_plus_sign:  `<main><h1 hidden>`
- [ ] does the FAQ CSS radio trick need some aria-controls hinting?

**Comment by arianvp** [comment]
Also check out the "Accessibility" Tab in FIrefox.


It found issues with the FAQ; namely that the  category selectors can not be activated using the keyboard

![image](https://user-images.githubusercontent.com/628387/85403197-40aeb980-b55d-11ea-8ba6-5ebf5ec6d924.png)
