### ISSUE TITLE
Suggestion for Improving App Download Conversion Rate

### ISSUE THREAD

**Issue by sjmclean24** [minvws/nl-covid19-notification-app-website#276]
The header at the top is ever-present in all the page templates. Yet, it currently only serves the purpose of showing the text ‘CoronaMelder’ and the logo.

It would be more beneficial from a conversion standpoint to group the logo and the text ‘CoronaMelder’ on the left part of the banner, whilst having the buttons ‘Download App’ on the right hand side.

This should benefit the conversion rate as :

- The option of downloading the app is ever-present throughout the Customer Journey. As a user who is traversing through the website, acquiring the necessary information to answer his origin intent and has arrived to the decision to install on the phone - the option to do so is on the page and does not need to travel through the website or search for it on the app store;

- Users may land on internal pages, rather than the Home Page, especially if they are referred from Search Engines or external websites. Such users may simply want to download the app directly on their phone without browsing the website. Having the ever-present download functionality, they can do so with ease as it will be directly on the page they landed.

https://www.onelink.to/ can be used so that one link is generated and placed behind one button, whereby the user is redirected to the Apple Store if he’s on iOS, or to the Play Store if he’s on Android. A fallback URL can be set for users who are not on any of these devices. It can be partially set to the Home Page, or an additional FAQ page placed with the relevant information as to why the user has landed on that page. This also carries the advantage of being able to issue a QR Code which can be used in printed material, thus aiding promotion on advertising campaigns, such as print and offline materials or video commercials.

**Comment by NL-William** [comment]
Using a third party like onelink will introduce risks (eg. they might alter the destination, etc.). The idea makes sense, but the logic behind it should be on the webserver itself.

**Comment by sjmclean24** [comment]
@NL-William yep, I agree with you there regarding implementing this functionality on the server itself rather than introducing a 3rd party dependency.

I think it would be more interesting if there could be a central repo available for a function like this, which can be self-hosted through a Govt institution and made available for use for the different ministries.

**Comment by anneke** [comment]
Hi, thanks for this suggestion! I'm putting it in front of the right people at VWS :)

**Comment by anneke** [comment]
@sjmclean24 Hi Steven, haven't forgot about this suggestion! Right now we have an open pull request to add a meta tag that opens a download banner when you visit the site on an iPhone. I think that would provide the functionality we are looking for? 
I've been hesitant to merge it becauseI haven't had a moment to check the app ID used in the pull-request.

**Comment by sjmclean24** [comment]
@anneke the Open PR being referred to is : https://github.com/minvws/nl-covid19-notification-app-website/pull/289/. Both this Issue and the PR 289 would contribute towards achieving the goal of increasing the App Download CTRs.

The Open Download Banner within #289 natively displays at the top of the page (on iOS only) and once the close button is clicked, it does not show again, until that state on the browser is lost. Apple did this to ensure that this is not annoying to users.

In this issue #276, the remark is more about using the screen real estate to have a constant CTA within the page structure so that at any point in the customer journey, the user can have a shortcut to download the app on the same page, rather than having to navigate to the Home Page from his current position to find the Download Link. Here I also go one step further and make a proposition on how we can make it easier for the user so that instead of having to choose between Apple Store and Google Play, we provide him with a link which sends him to the correct store based on the phone he's using.

For #289, indeed please verify that the App ID is correct :)

Let me know if you need further information on this!

**Comment by anneke** [comment]
Sorry @sjmclean24 , I was a little frazzled, we've been working hard on the app this past week! 

I have just merged number #289 after checking with my superiors if we wanted this. (Reply, enthousiastic yes :) ). I will forward them the other suggestion described above as well.

**Comment by sjmclean24** [comment]
@anneke no issues - I can imagine :)

Thanks for the work you are doing (even on a Saturday!)

**Comment by anneke** [comment]
Hi Steven, @sjmclean24  :) It's been a while and unfortunately I have had no more input on the design of the site. The focus is now completely on informing the public through the frequently asked questions and sharing information on the number of downloads. (You can find app downloads per store here as well, by the way: https://github.com/minvws/nl-covid19-notification-app-statistics/blob/main/statistics/appstore_statistics.csv ). 
Because of this deferred focus and the stage that we're in I think I will close this issue, but I will certainly keep it in mind if I hear any redesigns are being discussed!
