### ISSUE TITLE
Best A11Y video?

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-website#28]
Probably do native `<video>` :heavy_plus_sign: [`video.js`](https://github.com/videojs/video.js/) add-on?

**Comment by EdoPlantinga** [comment]
Corresponds to requirement 5 in [readme](https://github.com/minvws/nl-covid19-notification-app-website/blob/master/README.md#features-requirements-and-standards)

**Comment by EdoPlantinga** [comment]
Duplicate issue, closed

**Comment by bwbroersma** [comment]
Normally you would close the newer issue :wink:, but the newer issue has more information, so ok.

**Comment by EdoPlantinga** [comment]
Forgive me :-)
