### ISSUE TITLE
Form feedback repsonse

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-website#29]
In the current design there are some things:
- [ ] Respond on this subject? / *<span lang="nl">Reageren op dit onderwerp?</span>*
- [ ] Has your question been answered? / *<span lang="nl">Is uw vraag beantwoord?</span>*
- [ ] Send question / *<span lang="nl">Verstuur vraag</span>*

All can easily be done with calls to external services, that can send email or post a slack message (API call), but we need to choose a channel and a person responsible to handle e.g. new questions.

**Comment by bwbroersma** [comment]
Done? What is the idea how this will be done?

**Comment by EdoPlantinga** [comment]
@mellewynia Is this one still in the current design? Re-open if necessary.
