### ISSUE TITLE
CSP header aanpassen vanwege weghalen Piwik tellers

### ISSUE THREAD

**Issue by gberkouwer** [minvws/nl-covid19-notification-app-website#292]
Sinds de Piwik tellers zijn weggehaald is de aanroep naar statistiek.rijksoverheid.nl verdwenen. Deze hoort duis uit de CSP gehaald te worden.

`content-security-policy: default-src 'self' statistiek.rijksoverheid.nl; img-src 'self' statistiek.rijksoverheid.nl data:; style-src 'self'; script-src 'self' statistiek.rijksoverheid.nl; font-src 'self' statistiek.rijksoverheid.nl data:; object-src 'none';`

**Comment by anneke** [comment]
Hoi, ik heb dit doorgegeven (net als de andere openstaande security en hosting issues)!

**Comment by anneke** [comment]
Dit wordt door @mellewynia opgepakt!

**Comment by gberkouwer** [comment]
Top, zie deze @mellewynia :-) https://csp-evaluator.withgoogle.com/

**Comment by anneke** [comment]
Deze CSP header is uitgeschakeld, daarom sluit ik dit issue!
