### ISSUE TITLE
Gebruik van PKI-overheid certificaat overwegen ipv Sectigo

### ISSUE THREAD

**Issue by gberkouwer** [minvws/nl-covid19-notification-app-website#309]
Zou het niet beter zijn een PKI-overheid certificaat in te zetten, om afzenderschap, betrouwbaarheid en echtheid van deze belangrijke overheidswebsite in Nederland te ondersteunen?

**Comment by gberkouwer** [comment]
Deze is voor Coronamelder.nl gerealiseerd zie ik? Maar op coronamelderS.nl staat raar genoeg nog een Sectigo certificaat?

**Comment by EdoPlantinga** [comment]
Ik heb Brenno even gepingd hierover, zelf niet meer werkzaam aan CoronaMelder.

**Comment by nicktencate** [comment]
Destijds is er gekozen om PKIO te gebruiken voor officiele domeinen. Voor redirect domeinen (ie: geen data op het domein zelf) is dit niet verplicht.

Sinds PKIO niet meer bestaat, zijn deze vervangen door EV/OV certificaten.

Beide domeinnamen zijn inmiddels redirects geworden.
