### ISSUE TITLE
SEO stuff

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-website#32]
Add to `<head>`:
- [x] Generate alternative language links `<link rel="alternate" hreflang="en" href="en">`
- [ ] Add `<link rel="canonical" href="">` and `<meta name="og:url" content="">` (see `jekyll-seo-tag`)

Add JSON-LD for (maybe see `jekyll-seo-tag`):
- [ ] [app/play store links](https://developers.google.com/search/docs/data-types/software-app)
- [ ] [breadcrumb](https://developers.google.com/search/docs/data-types/breadcrumb)
- [ ] [special COVID-19 announcements? (beta)](https://developers.google.com/search/docs/data-types/special-announcements)

Jekyll plugins to enable:
- [x] [jekyll-sitemap](https://github.com/jekyll/jekyll-sitemap#note-on-use-with-github-pages-gem)
- [x] [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag#what-it-does)

***Note:** if we use the auto Jekyll build for GitHub Pages (and not a GitHub action to build the GitHub Pages) we can only use [these](https://pages.github.com/versions/) plugin versions.*

**Comment by anneke** [comment]
We zijn op dit moment druk met het ontwikkelen en uitrollen van de nieuwe homepage en vertalingen, maar ik ga hier deze week nog even naar kijken!

**Comment by anneke** [comment]
Ik heb jekyll-sitemap net toegevoegd aan de #297 branch, we hebben al een groot aantal meta tags dus ik moet even kijken hoe we de SEO plugin zouden kunnen configureren of dat het toch makkelijker is om de JSON-LD en canonical link zelf toe te voegen!

**Comment by anneke** [comment]
Ik sluit deze, en maak een nieuwe issue aan om jekyll-seo-tag in te stellen en te configureren, dat lost dan de rest van deze issues op!
