### ISSUE TITLE
Vertalingen teksten

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#322]
Overzicht:
https://docs.google.com/spreadsheets/d/16sQlmgAXohjEaa_JSa13AL6xr45EweKVeA6KYgVKRHQ/edit#gid=0

** VERVALT Definition of done Fase 1 (vóór lancering CoronaMelder app, vóór stemming in kamer)**
- [x] Teksten NL en EN zijn compleet en zijn inhoudelijk gelijk
- [x] EN teksten gevalideerd door vertaalbureau
- [x] In titeltekst staat 'CoronaMelder wordt getest in de praktijk'
- [x] Introductie alinea met 'de app wordt getest'
- [x] FAQ's beschikbaar over regiotest

**Definition of done Fase 2 (vóór lancering CoronaMelder app, na goedkeuring in kamer)**
Wijzigingen (NL en EN):
- [x] In titeltekst staat iets als:  'Vanaf xx is CoronaMelder in heel Nederland te gebruiken'
- [x] Introductie alinea met iets als: 'Vanaf xx is CoronaMelder in heel Nederland te gebruiken'
- [x] Toevoegen aan FAQ's over regiotest: 'Vanaf xx is CoronaMelder in heel Nederland te gebruiken'
- [x] Akkoord Lieke

**Definition of done Fase 3 (ná lancering CoronaMelder app)**
- [ ] Titeltekst conform ontwerp Joris
- [ ] Introductie alinea Titeltekst conform ontwerp Joris
- [ ] FAQ's over regiotest verwijderen
- [ ] Vertalingen in andere 8 talen buiten EN en NL zijn beschikbaar 

- [ ] 3 video's beschikbaar & toegankelijk , incl. vertaalde ondertitels alle talen

**Comment by SoessieSo** [comment]
Definition of done Fase 2: Voorleggen homepage, top 6 van vrane en fase 1 (vervalt), 2 en 3 voorleggen aan Lieke de Reus
