### ISSUE TITLE
Jekyll Seo-tag plugin toevoegen en instellen

### ISSUE THREAD

**Issue by anneke** [minvws/nl-covid19-notification-app-website#327]
Deze plugin voegt canonical links toe en JSON-LD schema structuur. Zie ook de oudere issues #32 en #313 .

(Als je hiervoor een bijdrage wil doen, graag in een feature branch op basis van develop!)

**Comment by damewold** [comment]
Hi @anneke I would love to try fix this but do you more instruction besides creating a feature branch to solve the problem?

**Comment by anneke** [comment]
Hi Denis, thanks! Well, we are currently creating branches off the develop branch, as that contains version 3.00 of the CoronaMelder website. The rest that I could and would gladly explain depends on your knowledge level :)

One caveat is that we require all commits to be signed. Let me know if you need more info- you can hit me up on the Code4NL slack or mail me at mail@annekesinnema.nl ws well :)

**Comment by damewold** [comment]
I checked out your website and I really love the mission and purpose of the CoronaMelder website. It will be great if I can contribute in anyway possible. Thank you for providing some explanation and being open to more questions. I will ask you directly through email if I experience any issue or need more clarification. Thank you
