### ISSUE TITLE
Include or link to README.i18n.md

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-website#33]
The [`README.md`](https://github.com/minvws/nl-covid19-notification-app-website/blob/b7e8d5df9aa021e7b2e4d78c3289ec791d0c48ce/README.md#translation) should preferably include or otherwise at least link to [`README.i18n.md`](https://github.com/minvws/nl-covid19-notification-app-website/blob/b7e8d5df9aa021e7b2e4d78c3289ec791d0c48ce/README.i18n.md).

**Comment by mellewynia** [comment]
Thanks. Closed.
