### ISSUE TITLE
App-store links voor verschillende talen dubbelchecken

### ISSUE THREAD

**Issue by anneke** [minvws/nl-covid19-notification-app-website#331]
We hebben de vraag uitstaan bij het app-team om er achter te komen of de links naar de app-stores (Apple en Android) nog verschillen voor andere talen, zodat we dit kunnen meenemen in de vertaalslag.

**Comment by lauraengelshove** [comment]
Ik krijg door dat de urls voor Android kloppen en dat de app-pagina naar de taal van je apparaat kijkt om je de juiste versie voor te schotelen. De taal staat niet in het URL voor de play store en wordt op basis van de browser of instellingen van het device bepaald.

**Comment by anneke** [comment]
Bedankt @lauraengelshove !
