### ISSUE TITLE
Fix HTML errors

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#333]
Fix errors at
https://validator.w3.org/nu/?doc=https%3A%2F%2Fminvws.github.io%2Fnl-covid19-notification-app-website%2Fen%2F

**Comment by anneke** [comment]
Ik heb een pull-request klaargezet om deze op te lossen: #336

**Comment by mellewynia** [comment]
Tweede pull request klaargezet met nog een aantal extra fixes: #339

**Comment by anneke** [comment]
Geverifieerd, de validator ziet geen issues meer. 👍
