### ISSUE TITLE
Inrichten branches extra talen, extra FAQ's, video's.

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#349]
Er komt zaterdag een contentwijziging (testregio's FAQ's en referenties eruit, titel wijzigt). 
Hoe kunnen we de extra talen die we dan willen hebben vast in concept klaar zetten, zonder dat ze al zichtbaar zijn bij een volgende publicatie? 
We verwachten ook extra FAQ's die we graag in de loop van de week van 5 oktober live willen kunnen zetten, evenals de video's. 
@Anneke kun je dit op een goede manier inrichten?

**Comment by anneke** [comment]
Jazeker, ik heb daar al iets voor!

Ik heb een github branch waar ik het afgelopen weekend al een voorzet in heb gemaakt voor de vertalingen.

Ik heb ook een branch waarin ik alleen de tekstwijzigingen heb die we moeten doen op de dag van livegang: aanpassen van de homepage titel en intro bijvoorbeeld, inderdaad het weghalen van de verwijzingen naar de testfase enzovoorts. Ik zet hier morgen die vertalingen bij (want die gaan ook allemaal uit van het compleet live zijn van de app), en voeg de vertalingen toe die we tot nu toe hebben. @EdoPlantinga
