### ISSUE TITLE
Koppenstructuur homepage 

### ISSUE THREAD

**Issue by julezrulez** [minvws/nl-covid19-notification-app-website#351]
### Kop Veelgestelde vragen heeft geen content (SC 1.3.1)

De kop "Veelgestelde vragen" is van niveau 2.
De veelgestelde vragen die eronder staan moeten dan een kopniveau 3 moeten hebben zodat ze bij de kop "Veelgestelde vragen" horen.

### To Reproduce
Ga in de browser op de homepage staan
Gebruik de plugin "headinsMap"
Kijk of de structuur logisch is.

### Expected behavior
H2 Veelgestelde vragen
H3 alle 6 de onderliggende vragen

**Comment by anneke** [comment]
Hoi @julezrulez , verdorie, ik dacht dat ik die al had aangepast! 

Wat denk je er trouwens van als we de vijf uitlegteksten _("Waarom is de app belangrijk?
Help de verspreiding van het coronavirus te stoppen", "Hoe werkt het?
Je krijgt een melding nadat je extra kans op besmetting hebt gelopen")_ ook niveau h3 geven, en er een h2 heading (visually-hidden) tussen zetten om die stukjes te groeperen?

**Comment by mellewynia** [comment]
Dit is aangepast. Ik sluit deze issue. Bedankt @julezrulez !
