### ISSUE TITLE
Is the subtitle correct?

### ISSUE THREAD

**Issue by jsoeterbroek** [minvws/nl-covid19-notification-app-website#36]
Is the subtitle 'Alleen Samen zorgen we voor minder besmettingen' correct?

Should it not be 'Alleen samen zorgen we voor minder besmettingen' (with a lowercase s)?

**Comment by bwbroersma** [comment]
Probably lower case `s`, at least currently that's the case on https://www.rijksoverheid.nl/
<img alt="screenshot of rijksoverheid.nl" src="https://user-images.githubusercontent.com/4252918/85743556-6b874200-b704-11ea-8c19-79f73748ff77.png" width="538">

**Comment by mellewynia** [comment]
@jsoeterbroek , dit vroeg ik me ook al af. Ik heb het nagevraagd: moet inderdaad met kleine s.
