### ISSUE TITLE
Idee voor de app: QR code scanner (om achterlaten gegevens bij horeca minder omslachtig te maken)

### ISSUE THREAD

**Issue by patryk1502** [minvws/nl-covid19-notification-app-website#374]
### Describe the bug, issue or concern

Beste Rijksoverheid, Kunnen jullie in de app een functie toevoegen waarmee je bij horeca zaken bijvoorbeeld een QR code scant in plaats van al je gegevens te moeten achterlaten? Zo weet de app dat je op die locatie bent geweest en kan de app je contacten ipv de horeca. Mensen zullen dan meer gemotiveerd zijn de app te gebruiken en de horeca heeft hierdoor weer meer tijd voor hun corebusiness. Daarnaast hoeven mensen zo hun persoonlijke gegevens niet bij horeca gelegenheid achter te laten. Mensen die de app niet hebben kunnen zichzelf altijd alsnog inschrijven.

Dear National Government, Can you add a function to the app that allows you to scan a QR code for catering establishments, for example, instead of having to leave all your details?  This way the app knows that you have been at that location and the app can contact you instead of the catering industry.  People will then be more motivated to use the app and the hospitality industry will have more time for their core business.  In addition, people do not have to leave their personal details at a catering establishment.  People who do not have the app can always register themselves.

E.g.

**Comment by anneke** [comment]
Hee @patryk1502 , bedankt voor je suggestie! 
Ik had toevallig deze suggestie gezien in de AppStore (was jij dat? :) ) en omdat ik het ook een goed idee vond [heb ik deze suggestie doorgespeeld](https://twitter.com/asinnema/status/1314671113121804295) naar de collega die het project management doet van de app, @reinier . 

_"Ja, meer mensen vinden het een goed idee, want staat al op het backlog. Hier moet echter goed naar privacy worden gekeken, dus het zit er niet zomaar in."_

Het 'backlog' is een lijst suggesties die het team gebruikt om ideeën uit te halen, te toetsen op haalbaarheid en vervolgens voor te stellen bij het Ministerie van VWS om het mee te nemen in de ontwikkeling van de app. 

Omdat dit geen issue heeft die betrekking heeft op de website, sluit ik deze, maar weet dus dat je vraag gezien is! :)
