### ISSUE TITLE
Bug: various issue with mediaplayer

### ISSUE THREAD

**Issue by anneke** [minvws/nl-covid19-notification-app-website#376]
"De .srt bestanden hebben vreemde karakters, dat is niet handig. Misschien zijn ze niet als UTF8 opgeslagen."

Nog een bug ontdekt door Gerrit Berkouwer: blijkbaar hebben de ondertitelingsbestanden vreemde karakters. 
Dit gaan we ook zo snel mogelijk bekijken!

Hiernaast lijkt het er op dat versie 4.2.16 van de mediaplayer die we gebruiken een aantal bugs introduceert op Android telefoons die niet voorkwamen op versie 4.2.6 die op rijksoverheid.nl gebruikt wordt. Mogelijk worden beide zaken opgelost met een downgrade.

**Comment by anneke** [comment]
Mental note: Ik kan me ook voorstellen dat dit te maken heeft met het lettertype, en dat het door ons gebruikte lettertype op de website bepaalde karakters niet bevat.

**Comment by EdoPlantinga** [comment]
@anneke vermoed dat je de versienummers hebt omgedraaid. Als er geen security issues zijn voor een downgrade, dan kan die wmb doorgevoerd. Morgen gaat @bramd een accessibilytest uitvoeren, dus lijkt me handig als dat voor morgen kan. Dan hebben we gelijk het certificaat binnen. Lukt dat denk je? @mellewynia?

**Comment by anneke** [comment]
Ik weet niet zo goed hoe deze in elkaar zit - @mikecodo is dit iets waar jij in kunt helpen?

**Comment by mellewynia** [comment]
@anneke, @EdoPlantinga , Android issue met selectie van ondertiteling: oorzaak bleek een soort race conditie. De ondertiteling was wel te selecteren, maar dit was zeer lastig. Dit komt door een bug in de mediaelement.js library: zodra je een taal kiest, dan ligt de focus van de knop 'af' en sluit deze het taalmenu. Door de volgorde waarop de events binnen komen, wordt het verdwijnen van de focus (blur) eerder afgehandeld dan de tap (klik) in het keuzemenuutje. Op desktop is dit ook te reproduceren in Chrome met het responsive modus aan in de ontwikkelaar tooling.

De oplossing hiervoor vergt een wat grotere wijziging binnen mediaelement.js. Gelukkig was er ook een instelling, waarmee de knop als een toggle-knop werkt. Ofwel: zolang we maar één taal voor de ondertiteling is dat voldoende. Zie hier de PR: https://github.com/minvws/nl-covid19-notification-app-website/pull/394

**Comment by mellewynia** [comment]
@EdoPlantinga PR is gemerged met Android update, staat op productie met versie 5.0.4 !

@anneke , wat is de status van de andere opmerkingen?

**Comment by anneke** [comment]
Ik ben van de andere opmerkingen niets meer gehoord - over de vreemde tekens. Ik ga het komende week even navragen, mogelijk kunnen we deze issue dan sluiten.

**Comment by EdoPlantinga** [comment]
@anneke kan deze gesloten?
