### ISSUE TITLE
FAQ needs update

### ISSUE THREAD

**Issue by arjank** [minvws/nl-covid19-notification-app-website#378]
### Describe the bug, issue or concern

The FAQ still shows the regions in which the app can be used, but the information is outdated.

### To Reproduce
1. Go to https://coronamelder.nl/nl/faq/2-hoe-helpt-coronamelder-tegen-corona/
2. Scroll down to the end of the text

### Expected behavior
I would expect the information to be correct, not outdated.

### Screenshots
![Screenshot showing the problem](https://user-images.githubusercontent.com/457006/95652638-d8c3b500-0af2-11eb-88a3-7843285ec74c.png)

### Additional context
The problem is not present in translations of the page, only in the Dutch version.

I have not done a complete search for similar content in other locations.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by anneke** [comment]
Ah! Achterblijvertje. Halen we z.s.m weg! :) Bedankt Arjan ;)

**Comment by arjank** [comment]
> Ah! Achterblijvertje. Halen we z.s.m weg! :) Bedankt Arjan ;)

Je kunt eventueel mijn PR gebruiken. Scheelt weer iets ;)

**Comment by anneke** [comment]
De PR is gemerged! Dankjewel :)
