### ISSUE TITLE
Inhoud test-en-onderzoeksversie-in-app.md

### ISSUE THREAD

**Issue by arjank** [minvws/nl-covid19-notification-app-website#382]
Als het bestand [`test-en-onderzoeksversie-in-app.md`](https://github.com/minvws/nl-covid19-notification-app-website/blob/production/nl/test-en-onderzoeksversie-in-app.md) (in alle talen) nog gebruikt wordt, moet de tekst van het bestand worden herzien.En als het bestand niet meer gebruikt wordt, is het beter om het te verwijderen. Dat voorkomt dan weer verzoeken tot het aanpassen ervan :wink:

**Comment by anneke** [comment]
Volgens mij kunnen we hem binnenkort ophalen! Staat op het lijstje om te checken komende week!

**Comment by anneke** [comment]
Nog een vraag voor het appteam @reinier @ijansch :)

**Comment by anneke** [comment]
Ik heb hier van een van de app ontwikkelaars de reactie op gekregen dat we het veiligste nog even de pagina kunnen laten staan, "We weten niet helemaal zeker of bij alle gebruikers de link naar deze pagina al weg is. Het kan even duren voor iedereen die update heeft gekregen."

**Comment by EdoPlantinga** [comment]
@reinier Kunnen we deze pagina inmiddels weghalen?

**Comment by reinier** [comment]
Ja, hij kan weg @EdoPlantinga @anneke 🎉

**Comment by EdoPlantinga** [comment]
Ok top, pak jij m op @anneke ?

**Comment by anneke** [comment]
Dit is even blijven liggen (gezien en vergeten), maar is ondertussen opgepakt!
