### ISSUE TITLE
FAQ overzicht bevat geen FAQ's van homepage

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#386]
De FAQ's die op de homepage staan, staan niet in het FAQ overzicht. Die zou ik daar wel verwachten.

**Comment by anneke** [comment]
Dit hebben we vorige week zo overlegd en ook afgesproken, omdat je anders ander gedrag krijgt op de vertaalde pagina's (in de talen arabisch, bulgaars, duits, frans, spaans, pools, roemeens en turks) waar je een aantal vragen in de ene taal krijgt en de rest in het engels. Mochten we hier een uitzondering voor willen maken in nederlands en engels kan dat, laten we dat even bespreken tijdens de standup dinsdag!

**Comment by anneke** [comment]
Ik kreeg hier mail over ook van Susan, en ik heb dit opgepakt voor Nederlands en Engels (zodat je daar wel alle vragen ziet, ook die op de homepage).

**Comment by EdoPlantinga** [comment]
Top! Hadden we elkaar even verkeerd begrepen blijkbaar.

**Comment by anneke** [comment]
Ja, sorry! :)
