### ISSUE TITLE
CSP toepassen op de website

### ISSUE THREAD

**Issue by gberkouwer** [minvws/nl-covid19-notification-app-website#392]
Overweeg een goede en stricte Content Security Policy toe te passen op de website, op zowel het hoofddomein als op het www-domein. Reden: security risico's verkleinen. Zie wat info op bv https://hackdefense.nl/publicaties/csp-het-hoe-en-waarom-van-een-content-security-policy/. Zie ook bv coronadashboard.rijksoverheid.nl waar een CSP is ingesteld. De CSP testen kan op https://csp-evaluator.withgoogle.com/.

**Comment by mellewynia** [comment]
@gberkouwer , hier ben ik het volledig mee eens. Bedankt voor de attentie ! Ik ga er werk van maken.

**Comment by anneke** [comment]
@mellewynia Heb jij hier nog werk van gemaakt? :)

**Comment by nicktencate** [comment]
Coronamelder website is inmiddels niet meer in de lucht. CSP headers waren wel in 2021 en 2022 aangepast.
