### ISSUE TITLE
404 pagina kapot?

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#397]
![afbeelding](https://user-images.githubusercontent.com/47494631/95876617-89d88280-0d73-11eb-92de-5d99c4228015.png)
Deze wordt nog door Google gevonden: 

https://coronamelder.nl/nl/statements/3-wat-als/

**Comment by EdoPlantinga** [comment]
Removal aangevraagd bij Google via https://www.google.com/webmasters/tools/removals.

**Comment by mellewynia** [comment]
Deze is inderdaad kapot. Ik ga de instellingen met Joeri even doornemen!

**Comment by mellewynia** [comment]
Het is opgelost! 🎊
