### ISSUE TITLE
 404-page does not render correctly

### ISSUE THREAD

**Issue by jsoeterbroek** [minvws/nl-covid19-notification-app-website#40]
### Describe the bug, issue or concern

404-page does not render correctly

### To Reproduce
1. Go to 'https://minvws.github.io/nl-covid19-notification-app-website/dinges'

### Expected behavior
minimal 404-page

### Screenshots

![screenshot](https://user-images.githubusercontent.com/1607771/85841564-9625d900-b79e-11ea-96ec-64e5bc84150c.png)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by jsoeterbroek** [comment]
Merged, closing issue

**Comment by EdoPlantinga** [comment]
Reopened by Edo & @mellewynia , some points remain
