### ISSUE TITLE
Toevoegen Huawei logo en link

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#403]
Graag Huawei logo toevoegen bij onderste download knoppen bij vertoning op desktops.
 ![afbeelding](https://user-images.githubusercontent.com/47494631/95996984-93c1ba80-0e33-11eb-9547-18e3440db7b6.png)

**Definition of done**

- [x] Graag Huawei logo toevoegen bij onderste download knoppen bij vertoning op desktops.
- [x] Voor verkeer dat komt vanaf Huawei toestellen: toon alleen de Huawei App Gallery en Google Play Store knoppen op de 3 plekken op de pagina. Detecteren door te zoeken op de string HUAWEI (case insensitive) of GMS in de User Agent String van de browser. 
- [x] Vertalingen van Appgallery knoppen toevoegen in de beschikbare talen. 
- [x] Duits/Roemeense knoppen toevoegen

Mail Huawei:
"In Huawei Browsers is het redelijk makkelijk het onderscheid te maken. GMS heeft GMSCore en HMS heeft HMSCore. Op basis daarvan kunnen alle logo’s uit voor HMSCore (totdat de app wel daarop werkt), en kan het AppGallery logo als enige getoond worden met GMSCore toestellen.

Voorbeeld HMS (P40 lite): Mozilla/5.0 (Linux; Android 10; JNY-LX1; HMSCore 5.0.3.304) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 HuaweiBrowser/11.0.2.303 Mobile Safari/537.36

Het is mogelijk om andere browsers te gebruiken op Huawei toestellen, maar dat zal zeer ingewikkeld worden. Voor nu is het bovenstaande voldoende. "

![Badge-Black](https://user-images.githubusercontent.com/47494631/96144141-23369e80-0f04-11eb-83f8-d0f7f36c5ab4.png)
![Badge-Black](https://user-images.githubusercontent.com/47494631/96144284-4a8d6b80-0f04-11eb-827d-b1acfbdbeca9.png)

**Comment by anneke** [comment]
@EdoPlantinga We hebben hiervoor eigenlijk de volgende zaken nodig om dit goed in te bouwen:

- Afbeelding in SVG formaat
- Link naar de appstore, dat zie ik nu niet staan; en zijn die verschillend per taal?
- Vertalingen van de alt-tekst lukte omdat een en ander gelijk is aan de Google App Store

**Comment by EdoPlantinga** [comment]
https://appgallery.huawei.com/#/app/C103008211. Taallink heb ik niet gekregen. Ik heb geen SVG gekregen, ik kijk nu even of ik uit de mail die ik eerder stuurde de .ai kan omzetten naar SVG, moment.

**Comment by anneke** [comment]
We hebben nu de Engelse en Nederlandse versie in SVG.
Voor het netst moeten we eigenlijk ook arabisch, bulgaars, duits, frans, spaans, pools, roemeens en turkse versies van de badge hebben. (Daar laat ik nu de Engelse zien, met vertaalde alt-text)

**Comment by EdoPlantinga** [comment]
Ah, mooi. 
Laten we voor de andere talen open staan voor pull requests.

**Comment by mellewynia** [comment]
De knop is toegevoegd, bedankt !

**Comment by EdoPlantinga** [comment]
Vandaag en gisteren heb ik met Melle, Bastiaan en Vincent gebeld over dit issue. Kort samengevat is het technisch niet mogelijk om met 100% zekerheid te detecteren of het verkeer van Huawei komt. In deze link https://developers.whatismybrowser.com/useragents/explore/operating_platform_string/huawei/, staat te lezen dat alle daar genoemde browsers "Huawei" of "HUAWEI" in de user agent string hebben staan.

**Comment by EdoPlantinga** [comment]
@mellewynia Definition of done toegevoegd hierboven

**Comment by mellewynia** [comment]
Zojuist aanpassingen gemaakt met de nieuwe DoD & de Huawei AppGallery buttons toegevoegd. Deze waren nog niet in het Duits en Romeens beschikbaar, die update volgt vermoedelijk nog later.

**Comment by EdoPlantinga** [comment]
Knoppen laatste talen staan erop, call afgesloten.
