### ISSUE TITLE
Hoverkleur bij veelgestelde vragen biedt te weinig contrast

### ISSUE THREAD

**Issue by anneke** [minvws/nl-covid19-notification-app-website#407]
1.4.11: Contrast van niet-tekstuele content:

Bij hover krijgt de veelgestelde vraag een andere achtergrondkleur. Deze heeft echter zeer laag contrast met het wit als er geen hover is. De kleur bij hover is #edf0f6. 
Welke vraag focus heeft is nu voor niet iedereen zichtbaar.

Suggestie: verhogen van het contrast of toevoegen van een outline-effect.

**Comment by laurasiecker** [comment]
Dank voor het doorgeven. Op dit moment is alles voor OSAGE even on hold gezet, dus zou dit even met Edo communiceren.

**Comment by EdoPlantinga** [comment]
@anneke Maak de achtergrondkleur maar wat lichter als je wilt, lijkt me de beste oplossing.

**Comment by anneke** [comment]
Nee, dat zou het contrast juist lager maken @EdoPlantinga :) Ik zou dan voorstellen om de achtergrondkleur donkerblauw te maken en de tekstkleur wit, zoals bij de veelgestelde vragen op de homepage als je op 'lees meer' hovert.

**Comment by EdoPlantinga** [comment]
Wellicht kijken we ergens anders naar, ik had het over deze hover: 

![afbeelding](https://user-images.githubusercontent.com/47494631/96594667-2908f700-12eb-11eb-85e2-2ebc5cfcd0f8.png)

En jij?

**Comment by anneke** [comment]
Het probleem was dat die hover achtergrondkleur te weinig contrast heeft, waardoor het voor mensen met een visuele beperking slecht te zien is waarop gehoverd wordt. Ik heb de achtergrondkleur nu donkerblauw gemaakt met daarop witte tekst, en dat levert volgens een collega (tijdelijke vervanger van Bram) genoeg contrast om het probleem op te lossen:

![Uploading Schermafbeelding 2020-10-21 om 12.18.36.png…]()
