### ISSUE TITLE
De preview van veelgestelde vragen is voor verbetering vatbaar

### ISSUE THREAD

**Issue by anneke** [minvws/nl-covid19-notification-app-website#426]
Dit is een afbeelding uit de Code4NL Slack, waar ik twee links naar de nieuwst toegevoegde veelgestelde vragen deelde. De preview is voor verbetering vatbaar.

<img width="582" alt="Schermafbeelding 2020-10-23 om 17 38 53" src="https://user-images.githubusercontent.com/7202272/97024066-a6846f80-1556-11eb-9562-8f3cfaeefd7f.png">

**Comment by JohJohan** [comment]
Lijkt me ook handig om de site titel te gebruiken voor de `og:titel` zodat het bij het delen duidelijk is wat de titel is van de url

**Comment by anneke** [comment]
Bedankt @JohJohan !

**Comment by davidhund** [comment]
Tipje: deze (OG) meta tags kun je makkelijk checken/genereren via https://metatags.io/

**Comment by anneke** [comment]
Bedankt @davidhund ! Ik was op het punt deze issue te sluiten want ik heb hier wel wat werk aan gedaan, maar er is wellicht nog extra winst te halen met die site :)
