### ISSUE TITLE
A/B testing: variations of the site are possible in the architecture (requirement 4)

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#44]
### Definition of done:
- [ ] The architecture makes it possible to have variations of the website code, sending part of the traffic to several variantions of the website, keeping track of clickthrough rates.

**Comment by mdraijer** [comment]
Richting die we nu zien (na overleg met DPC): elke pagina wordt geserveerd in 1 versie die mbv javascript A danwel B toont aan de gebruiker.
Ticket kan dus naar Melle.

**Comment by EdoPlantinga** [comment]
Works for me in principe. Uitzoeken na livegang stel ik voor.
