### ISSUE TITLE
Invoeren Coronamelder code op de uitslagpagina

### ISSUE THREAD

**Issue by ramondeklein** [minvws/nl-covid19-notification-app-website#449]
De impact van de Coronamelder applicatie is sterk afhankelijk hoe snel na het constateren van de besmetting de melding wordt rondgestuurd. Juist als er veel besmettingen zijn, dan duurt het lang (vaak meer dan 24 uur) voordat de GGD contact opneemt. Hierdoor wordt ook de melding pas later verstuurd en is daarmee minder doeltreffend.

Het zou een verbetering zijn om op de uitslagpagina ook de mogelijkheid te geven tot het invoeren van de code uit de Coronamelder app. Veel mensen die deze app gebruiken zullen ook online hun testresultaat controleren, dus daarmee zou je veel sneller een melding rond kunnen sturen en daarmee de app effectiever maken.

# Voorstel

- Als er een positieve test wordt gerapporteerd, dan kan men direct de code invoeren die vervolgens de melding rondstuurt. Omdat men wel ingelogt is met DigID is het theoretisch mogelijk dat er een privacy probleem is. Overigens is dat nu ook zo, want de GGD weet ook waarmee ze bellen. Ook dit gaat op goed vertrouwen.

**Comment by anneke** [comment]
Hoi Ramon, volgens mij is dit een suggestie voor coronatest.nl en niet zozeer voor coronamelder.nl , of begrijp ik je verkeerd? :)

**Comment by ramondeklein** [comment]
@anneke Je begrijpt me prima. De repo eindigde op "website", dus ik ging er vanuit dat dit die website betrof. Of is die niet open-source?

**Comment by anneke** [comment]
Niet dat ik weet, maar ik moet dat navragen! Dit is de  repo voor www.coronamelder.nl :)

**Comment by anneke** [comment]
Ik sluit deze issue, ik heb geen informatie kunnen vinden over open source zijn van https://coronatest.nl/
