### ISSUE TITLE
Configure hosting (requirement 7) (Luc)

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#45]
Corresponds to requirement 7 in [readme](https://github.com/minvws/nl-covid19-notification-app-website/blob/master/README.md#features-requirements-and-standards)

## Definition of done (at launch)
- [x] Resistant to DDOS attacks
- [x] Website is instantly scaleable to 1 million concurrent users (preferably cloud solution)
- [ ] The site can be reached via [appname-here].nl and www.[appname-here].nl
- [ ] Corresponds to to standards as defined in [requirement 7](https://github.com/minvws/nl-covid19-notification-app-website/blob/master/README.md#features-requirements-and-standards) 
- [x] Updates to code on github should be easily pushed to the live environment
- [x] PKI overheid certificate (@Luc?)
- [ ] internet.nl test 

also see #71

## Additional definition of done post-launch
- [x] Website is instantly scaleable to 10 million concurrent users (preferably cloud solution)
- [ ] A/B testing should be possible (see other issue #44 )
- [ ] ... to be added to by Luc

**Comment by mellewynia** [comment]
Inmiddels contact gehad met Gerrit: de pipeline is ingericht! (cc: @EdoPlantinga)

**Comment by mdraijer** [comment]
PKIo certificaat wordt door SP geregeld. Zal maandag gedaan worden als Akamai ook ingericht wordt.
Test op internet.nl wordt idd gedaan, daarbij kun je ook vermelden ssllabs.com.
Domein met 'www.' ervoor wordt niet aangemaakt.

**Comment by bwbroersma** [comment]
> Domein met 'www.' ervoor wordt niet aangemaakt, op advies van AZ.

Interesting, ik gebruik juist altijd wél `www.`, geeft wat meer technische mogelijkheden i.v.m. `CNAME`, waarmee je zonder de `NS` uit handen te geven wel alles load balancen en Geo-IPen. Geen idee hoe Akamai werkt, maar mag hopen dat de DNS dan ook door Akamai wordt geregeld, anders zit je met round robin DNS op je apex domain, en moet je dus met anycast werken om dit beetje fatsoenlijk op te lossen.

**Comment by mdraijer** [comment]
Heb even verder doorgevraagd. Blijkt verkeerde interpretatie te zijn geweest. Zit volgens de domeinspecialisten van AZ zo:
* Heb je al een subdomein, bijv. corona.rijksoverheid.nl, dan is www een onnodig extra subsubdomein;
* Begin je met een top level domein, bijv. corona.nl, dan biedt een subdomein www voor de website voordelen boven het kale domein, ook qua cookies.

Nu zitten we met de situatie dat we al een PKIo certificaat hebben voor het domein, _zonder_ SAN voor www.

Dus is de vraag, misschien voor @mellewynia, of het in dit geval zo belangrijk is om dat extra www-domein te hebben dat we een nieuw PKIo certificaat moeten aanvragen (met de kosten en doorlooptijd vandien) of dat we ook zonder kunnen.

**Comment by bwbroersma** [comment]
Cookies zijn sinds HTTP1.2 niet meer echt een groot argument.
Een subdomain is geen apex domain en heeft dus deze limitaties niet (qua `CNAME`), dat klopt.
Als je nu toch een apex domain zonder `www.` wil gebruiken:
* kan je de CDN goed op je apex draaien omdat je geen `CNAME` opties hebt? Het 'lijkt' er op dat dit goed gaat vanuit extern gezien, maar ik kan de interne DNS setup /resolving /failover e.d. niet zien (ook bij DDoS).
* indien je straks een HSTS hebt zoals `Strict-Transport-Security: max-age=63072000; includeSubDomains; preload` en iemand typt `www.` in, dan gaat deze direct naar poort 443 om TLS te praten, maar ik begrijp dat je daar dan geen certificaat voor hebt? Als het antwoord nee is, dan kan je niet de `includeSubDomains` optie gebruiken en daarmee dus ook niet de `preload` optie.

**Comment by bwbroersma** [comment]
BTW ik heb een [_vermoeden_ ](https://twitter.com/BWBroersma/status/1280201940069167105) :wink:
Pro tips:
- dual cert (RSA + ECC)
- RSA 2048bit (géén 4096bit, is nl. 4 keer zo CPU intensief om op te zetten, je eigen soort van CPU DDoS)
- zowel apex als `www.`

_en ik zou `www.` als main gebruiken / naar redirecten_

**Comment by bwbroersma** [comment]
* [ ] Add [missing requirement DNSSEC](https://twitter.com/BWBroersma/status/1280215904442298369) _(part of internet.nl test)_.

**Comment by mdraijer** [comment]
DNSSEC: inderdaad deel van internet.nl test. We doen overigens ook SSL Labs.
www/niet-www vraagstuk: we gaan beide ondersteunen met niet-www als hoofddomein. Dus www wordt geredirect naar niet-www.
Er is een nieuw certificaat aangevraagd die de www-variant als SAN heeft.
De redirect wordt geregeld op het SP.

**Comment by bwbroersma** [comment]
Gek, waarom nu toch de apex gebruiken als main? Gezien:
* [het advies eerder](https://github.com/minvws/nl-covid19-notification-app-website/issues/45#issuecomment-654075720) juist wel `www.` subdomein was (vanwege mogelijke voordelen)
* dit volgens mij ongeveer nergens bij de overheid wordt gebruikt

**Comment by alexdekok** [comment]
[20200707 Compliancyrapport implementatie verplichte webeisen (Corona app Infosite).docx](https://github.com/minvws/nl-covid19-notification-app-website/files/4889126/20200707.Compliancyrapport.implementatie.verplichte.webeisen.Corona.app.Infosite.docx)

**Zie document als gedeeld door Luc met deze informatie 20200707 Compliancyrapport implementatie verplichte webeisen (Corona app Infosite):**

Bijgesloten heb ik een door mij gedeeltelijk ingevuld compliancyrapport voor de webeisen. Verzoek aan jullie om voor de webeisen steeds dit rapport te gebruiken, zodat we overzicht houden. We hanteren het pas-toe-leg-uit principe, waarbij de bewijslast van jullie samen moet komen. Wij (liaisons) toetsen o.a. op Internet.nl (web en mail), Powermapper.com, Ghostery.com, etc. Gaande weg is dat proces al bezig.
 
Akamai en SP/CS gaan morgen verder aan de slag om e.e.a. te configureren en ook een aantal rood gemarkeerde (technische) eisen op groen te krijgen. Er wordt gerekend op twee dagen doorlooptijd. Cara is hier trouwens over geïnformeerd. Safety first!

**Comment by alexdekok** [comment]
@mdraijer kun jij svp naar het document kijken wat hier is toegevoegd en al is ingevuld door Luc. Klopt alles rondom jullie werkzaamheden of missen er nog zaken?

**Comment by mdraijer** [comment]
Akamai is gisteravond ingericht. Staat nog wel dicht met IP-whitelisting zodat we testen kunnen uitvoeren.
Vanochtend getest met internet.nl, ssllabs.com en webpagetest.org. Door die eerste werden nog wat dingen gevonden, daar kijken we vandaag naar.
Het document van Luc heb ik gisteren doorgenomen. Volgens mij zijn alle punten waar we vanuit SP iets mee kunnen nu goed, behalve AVG: dat moet ik nog checken.
Ik maak vandaag een rapportje en stuur dat met het bijgewerkte comply/explain lijstje naar Luc.

**Comment by mdraijer** [comment]
Dat document zat trouwens al bij #71

**Comment by EdoPlantinga** [comment]
@mdraijer Kun je het vinklijstje van dit issue even bijwerken? Lijstje zelf is inmiddels wat ouder, wellicht kan het vervangen door het compliancy doc van Luc
