### ISSUE TITLE
Toegankelijkheidspagina bijwerken

### ISSUE THREAD

**Issue by bramd** [minvws/nl-covid19-notification-app-website#456]
### Describe the bug, issue or concern

De [toegankelijkheidspagina](https://www.coronamelder.nl/nl/toegankelijkheidsverklaring) is niet up-to-date. Het hierin genoemde onderzoek is inmiddels uitgevoerd. We kunnen deze bijwerken of de informatie enkel publiceren in de verklaring op toegankelijkheidsverklaring.nl. Deze is echter vrij lang en niet zo makkelijk leesbaar, dus ik wil voorstellen onze eigen pagina ook te behouden en bij te werken.

### Governance
- [X] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [X] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [X] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by anneke** [comment]
Hoi @bramd , ik ben het met je eens dat het het beste is om de eigen pagina te behouden en bij te werken. Heb je een inhoudelijke suggestie van hoe de content veranderd zou kunnen worden? Ik lees namelijk geen verwijzingen naar nog uit te voeren onderzoek, maar vooral globaal informatie over de intenties bij de bouw van de website. Hoor graag van je!

**Comment by bramd** [comment]
Hi @anneke. Het gaat vooral om deze twee bullets:

* Er zal een formeel toegankelijkheidsonderzoek plaatsvinden volgens de WCAG-EM standaard. Hierbij wordt getoetst op zowel functioneel-technische onderdelen als de redactionele aspecten. Gevonden knelpunten lossen wij duurzaam op.
* Planning onderzoek: Dit onderzoek wordt uitgevoerd op 15 oktober 2020.

Het onderzoek is inmiddels geweest en er zijn geen problemen gevonden, dus lijkt me goed dat te verwerken. Wellicht kan dat als aanvulling op het punt daarboven over automatische tests?

Verder was er een tijdje geleden discussie over de toegankelijkheid van de factsheets, ik weet niet zeker of dat al helemaal is opgelost. Zo niet, dan kunnen we dat wellicht het best noemen onder bekende problemen.

**Comment by anneke** [comment]
Dit is ondertussen afgerond, en wijzigingen zijn verwerkt met hulp van jouw collega Marjon!
