### ISSUE TITLE
Translations (content)

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#53]
[Desired translations are defined in this document](https://docs.google.com/document/d/15ucCK7UfM9ht418f26H14rm9TTQLrcioM3qLSq2DFV0/edit#)

## Definition of done
- [ ]  all languages are translated and loaded in the document
- [ ] change whatsapp/social media link content per language

**Comment by caszeegers** [comment]
Is er al duidelijk welke talen er bij de eerste live-gang worden meegenomen (en wanneer deze er dan zijn)?

**Comment by EdoPlantinga** [comment]
Martin gevraagd te antwoorden. Merk op dat er meerdere talen aan zitten te komen, dus de taalswitch zal wellicht iets anders moeten. 
CC @mellewynia

**Comment by mellewynia** [comment]
@EdoPlantinga , klopt. Komt er uiteindelijk uit te zien zoals in ontwerp v0.7

**Comment by jsoeterbroek** [comment]
Please note Arabic is an RTL (Right-to-Left) language, which may have unintended consequences for layout.
