### ISSUE TITLE
Vraag: Footer info

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#55]
Vraag van Alex: Op Rijksoverheidssites gebruiken ze normaliter onderstaande footers.  Ter info staan er voorbeelden van oplossingen bij van andere Rijksoverheidssites.

We moeten weten of de teksten die nu gebruikt worden, met een aanpassing naar de naam van de Corona App voldoende zijn. Martin zou dit kunnen navragen

Privacy: https://www.doemeemetmdt.nl/privacy
Cookies: https://www.doemeemetmdt.nl/cookies
Toegankelijkheid: https://www.doemeemetmdt.nl/toegankelijkheid
Kwetsbaarheid melden: https://www.iedereenondereendak.nl/kwetsbaarheid-melden
Contact: https://www.iedereenondereendak.nl/contact

**Comment by mellewynia** [comment]
Contactpagina toegevoegd. Zie: https://minvws.github.io/nl-covid19-notification-app-website/contact

**Comment by EdoPlantinga** [comment]
Please change www link to regular hyperlink, writing out www links is not WCAG compliant as far as I know.
