### ISSUE TITLE
Juiste APP icoon terug laten komen

### ISSUE THREAD

**Issue by alexdekok** [minvws/nl-covid19-notification-app-website#56]
### Juiste App icoon terug laten komen in het design van de website zodra dit helemaal final is

Zodra het app icoon 100% goed is, moeten we dit ook een plek gaan geven in de website ter referentie

### Expected behavior
Herkenning van de app in de site

### Referentie
Ter info: Dit is zoals het icoon er NU uitziet. Zodra dit akkoord is, oppakken. 
[
[Export.zip](https://github.com/minvws/nl-covid19-notification-app-website/files/4852666/Export.zip)
](url)

**Comment by bartlenstra** [comment]
@alexdekok Zou jij mij een vector-versie willen sturen als het icoon gereed is?
Of uiteraard anders ergens even plaatsen in Figma bij het design van de website?

https://www.figma.com/file/Dmo5nuXcaoxMaNTXDFc9Cw/Status-dashboard-COVID-19-notificatieapp?node-id=978%3A1155

**Comment by alexdekok** [comment]
ik zal een vector variant hier delen zodra hij echt def. def. is
