### ISSUE TITLE
AB-testing: Mogelijkheden met Piwik PRO / workaround

### ISSUE THREAD

**Issue by alexdekok** [minvws/nl-covid19-notification-app-website#57]
### Describe the bug, issue or concern

AB/Testing of dit mogelijk is met Piwik PRO of hoe lost Rijksoverheid dit normaliter op.

Personen die hierbij kunnen helpen zijn Martijn Warmoeskerken en Eva van Kruchten 

Martijn Warmoeskerken (m.warmoeskerken@minaz.nl) + Eva van Kruchten (e.vankruchten@minaz.nl)

### Expected behavior
Mogelijkheid tot AB-testen

**Comment by ph00lt0** [comment]
Men zou zelf heel simpel [Matomo](https://matomo.org/) kunnen installeren op eigen server. (Matomo is de opvolger van Piwik Analytics). Let wel goed op bij het configureren, dat de privacy van bezoekers gewaarborgd blijft. 

Hier kan men informatie vinden over de A+B testing: [matomo.org/docs/ab-testing](https://matomo.org/docs/ab-testing)

**Comment by alexdekok** [comment]
Rijksoverheid werkt met Piwik PRO, daar is al contact over geweest met Martijn en daar werd aangegeven dat Rijksoverheid geen Matomo gebruikt. Ook al is het van dezelfde partij.

**Comment by ph00lt0** [comment]
@alexdekok 
Ik denk dat dit hele open ontwikkelingstraject een goede mogelijkheid zou zijn om het juist helemaal perfect te doen. Daarmee dus geen derde partijen toegang te geven tot de informatie. Piwik PRO is een cloud dienst die, zover ik weet, inmiddels ook verouderd is. Dat zal uiteindelijk bij de rest van de overheid ook vervangen moeten worden. Dan liever gelijk in eigen beheer. De open ontwikkeling van de app lijkt mij de juiste tijd om een goed voorbeeld neer te zetten voor de ontwikkeling van andere diensten binnen de overheid.

**Comment by alexdekok** [comment]
@ph00lt0  ik snap wat je zegt, alleen we moeten ons natuurlijk ook houden aan policies die breder gaan dan dit open ontwikkeltraject. Ik zou daarin graag  met je meegaan, echter gezien beslissingsbomen en keuzes uit het verleden kunnen we ook niet alles realiseren zoals het in de ideale wereld zou werken. We zitten nu eenmaal voor doormetingen / AB-testing en dergelijke vast aan bepaalde zaken. Er vinden overigens nu wel gesprekken plaats hoe dit is op te lossen. Hier is o.a. Osage met wat stakeholders van Rijksoverheid ook mee bezig.

**Comment by mdraijer** [comment]
Woensdag besproken met DPC (Martijn, Eva), SP (Marco, Fernand) en Dev (Melle).
Het is duidelijk geworden dat A/B-testen mogelijk is met Piwik maar dat daar niets specifiek voor ingericht hoeft te worden.
De logica voor A/B komt in de pagina's zelf. Er is 1 Piwik-code en als argument wordt 'A' of 'B' (of iets dergelijks) meegegeven.
Dus geen actie voor Piwik => @alexdekok ticket kan gesloten worden?

**Comment by mellewynia** [comment]
Er is voor gekozen om Piwik.JS eruit te halen, daarmee is deze ticket outdated. Gesloten.
