### ISSUE TITLE
Checking kleurstettings/Rijksoverheid 

### ISSUE THREAD

**Issue by alexdekok** [minvws/nl-covid19-notification-app-website#58]
### 

Rijksoverheid gebruikt bepaalde kleursettings en plaats logo's bij digitale trajecten. Dat betekent dat vinkjes van het logo op de juiste positionering horen te staan en dat bepaalde kleuren gebruikt worden om ook toegankelijk te zijn. 

Kan iemand dit checken ahv. deze gegevens: https://www.rijkshuisstijl.nl/basiselementen/basiselementen-online 

Verder heb ik de juiste kleursettings van de app toegevoegd. Zien we hier een verschil in tussen bovenstaand. Als dat zo is moeten we eerst overleggen met Martin hoe hiermee om te gaan op de site.https://roorda.wetransfer.com/downloads/8815e6a904bcb6998ad6b246e6f9782420200630133912/aae286cd53fd78ef86b309eb2074197a20200630133913/d5d458

**Comment by bartlenstra** [comment]
De juiste kleurwaarden van Rijksoverheid zijn gebruikt in de website.
Gele header, RO-donkerblauw en kleur van het logo/vaantje.

**Comment by bartlenstra** [comment]
Niet duidelijk wat je bedoelt met 'vinkjes van het logo'. 
Wat ik kan zeggen over het logo/vaantje bovenaan de website (deze zijn in het design ook zo opgenomen):

Desktop: 50x100px
Tablet (90%):  45x90px
Mobile: (80%): 40x60px (verkort vaantje).

Deze info is overgenomen van de Rijkshuisstijlpagina betreffende plaatsing van logo op digitale middelen.

**Comment by alexdekok** [comment]
check! Vinkje is het vaantje, als de leidraard de Rijkshuisstijlpagina is geweest, dan is dit goed

**Comment by bartlenstra** [comment]
Volgens ons (Cas en ik) zijn de kleuren van de app, zoals die in de download zitten héél sprekend.
Echter vroegen wij ons af: deze zijn geen rijksoverheid-kleuren.

**Comment by alexdekok** [comment]
hi Bart, wat bedoel je zoals die in de download zitten?

**Comment by bartlenstra** [comment]
![IMG-20200630-WA0004 (1)](https://user-images.githubusercontent.com/67674717/86226600-2e033880-bb8c-11ea-8030-e77b27f9effc.jpg)

**Comment by alexdekok** [comment]
Ik zal dit even polsen bij Martin en anders denk ik dat het goed is dat we daar morgen tijdens de standup een opmerking over maken bij  Martin. Enerzijds zouden we ook kunnen kijken of dit wellicht ergens is op te lossen ahv. content. Kleuren lijken vrij veel op elkaar, alleen toch ook niet. Daarom had ik hem hier ook opgeschreven. Thanks voor het checken Bart!

**Comment by bartlenstra** [comment]
Ik zou het overigens heel zonde vinden als de kleuren van de app zouden moeten worden aangepast.
We vinden ze heel sprekend..

**Comment by alexdekok** [comment]
ik ook!

**Comment by bartlenstra** [comment]
https://www.rijkshuisstijl.nl/basiselementen/basiselementen-online/online-kleuren
