### ISSUE TITLE
Q&A battery use

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-website#67]
> **Loopt de batterij van mijn telefoon snel leeg door de corona-app?**
> Nee, de app verbruikt weinig energie. De app gebruikt Bluetooth Low Energy (Bluetooth Lage Energie). Dit is een speciale vorm van Bluetooth die weinig stroom gebruikt.
>
> Hoeveel procent van je batterij de app precies gebruikt, verschilt per telefoon.

_Source: [`_questions/how-it-works/nl/5-werking-batterij.md`](https://github.com/minvws/nl-covid19-notification-app-website/blob/1cfb22f9b81a06862e2b0540f64203dd22d739ee/_questions/how-it-works/nl/5-werking-batterij.md)_

The battery use is significant, at least on iOS, see [the document](https://docs.google.com/spreadsheets/d/1bJYMvBhyUYxjj3YhRYUbVHlBHPgSwfc1CtI1zy2n4XM/edit) about the iOS use, and the majority is above 10%. To state it **doesn't** use a lot of battery is saying 10% of battery use on a iPhone with a healthy battery is low. Which I would disagree, 10% is significant.

*Update: my current 10 day average of "Health - COVID-19 Exposure Logging" has fallen from 10+% to 5%, so that's positive, but still significant.*

**Comment by anneke** [comment]
Hi Benjamin, thank you for your feedback! We will take it into account, but for now, we decided to stick to our current statement.
