### ISSUE TITLE
Vertalingen voor in de Site (Chinees en Arabisch komen)

### ISSUE THREAD

**Issue by alexdekok** [minvws/nl-covid19-notification-app-website#68]
### De talen van de website komen eraan:

We moeten goed kijken naar de Arabische en Chinese taal. Dit wordt anders geschreven (links / rechts) en maakt natuurlijk gebruik van andere tekens. 

### Talen
Engels
Duits
Pools
Spaans 
Turks 
Papiamento
Arabisch (technisch checken!)
Chinees (technisch checken!)

### Verwachting aanlevering
Vrijdag 3 juli op zijn vroegst einde dag

**Comment by jsoeterbroek** [comment]
Please note Arabic is an RTL (Right-to-Left) language, which may have unintended consequences for layout.

**Comment by alexdekok** [comment]
Hi Jsoeterdonk, ik was nog bezig met dit ticket, scherp voor je aanvulling. Dat was namelijk ook mijn verder aanvulling.
