### ISSUE TITLE
A/B testing using a proxy CTA

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#70]
Goal: we want to be able to start A/B testing before the app is launched, so we can optimize the site beforehand. The idea is to use a temporary CTA button such as "Let me know when the app is launched". This button would link to a page with the social media accounts of the Ministry of VWS. That way we can start A/B testing at an early stage. 

## Definition of done
- [ ] There is a Call to Action button that is tracked, before launch of the app
- [ ] There is a page that is linked to by the CTA

Relates to requirement 4 in [readme](https://github.com/minvws/nl-covid19-notification-app-website/blob/master/README.md#features-requirements-and-standards)

**Comment by mellewynia** [comment]
Er is voor gekozen om Piwik.JS eruit te halen, daarmee is deze ticket outdated. Gesloten.
