### ISSUE TITLE
Continuous Integration (CI) testing

### ISSUE THREAD

**Issue by jsoeterbroek** [minvws/nl-covid19-notification-app-website#73]
### Continious Integration (CI) testing with Travis.

See also: https://jekyllrb.com/docs/continuous-integration/travis-ci/

I have create PR #74 with a solution for Travis and html-proofer.

**Comment by jsoeterbroek** [comment]
If and when PR #74 is merged, we will then need to change the status badge in README.md to point to the correct/current Travis config, once setup.

**Comment by jsoeterbroek** [comment]
Current (04 july 2020) html-proofer test output:

Build Failed:

` ./_site/en/example-content-page.html
  *  image ../img/logo-GGD.svg does not have an alt attribute (line 184)
  *  image ../img/logo-VWS-RIVM.svg does not have an alt attribute (line 181)
  *  image ../img/logo-VWS.svg does not have an alt attribute (line 178)
- ./_site/en/index.html
  *  image ../img/logo-GGD.svg does not have an alt attribute (line 387)
  *  image ../img/logo-VWS-RIVM.svg does not have an alt attribute (line 384)
  *  image ../img/logo-VWS.svg does not have an alt attribute (line 381)
- ./_site/index.html
  *  image  does not have an alt attribute (line 89)
  *  image  does not have an alt attribute (line 105)
  *  image  does not have an alt attribute (line 121)
  *  image  does not have an alt attribute (line 138)
  *  image  does not have an alt attribute (line 153)
  *  image has no src or srcset attribute (line 89)
  *  image has no src or srcset attribute (line 105)
  *  image has no src or srcset attribute (line 121)
  *  image has no src or srcset attribute (line 138)
  *  image has no src or srcset attribute (line 153)
- ./_site/privacy.html
  *  External link https://unpkg.com/swiper/js/swiper.js failed: 404 No error
htmlproofer 3.15.3 | Error:  HTML-Proofer found 17 failures!`

**Comment by dirkx** [comment]
Ziet er goed uit. @mellewynia gaat maandag even achter het travis-ci aspect aan en of het Misterie liever een paid account wil met alle safeguards, (dingen als retentie, gdpr/avg, etc) of dat de open-source versie ok is.

**Comment by jsoeterbroek** [comment]
> Ziet er goed uit. @mellewynia gaat maandag even achter het travis-ci aspect aan en of het Misterie liever een paid account wil met alle safeguards, (dingen als retentie, gdpr/avg, etc) of dat de open-source versie ok is. Een andere optie is wat scripten met Github Actions.

Wat is hier uit gekomen?

**Comment by arianvp** [comment]
Je kunt ook de CI van https://github.com/minvws/nl-covid19-notification-app-community-website jatten (op basis van Github actions)

Doet nu alleen een check dat Jekyll geen syntaxfouten heeft

**Comment by anneke** [comment]
We hebben overlegd of dit nog meerwaarde zou bieden binnen het proces waarin we werken, maar hebben besloten om deze issue voor nu te sluiten. We zijn nog met twee features bezig en verwachten daarna de vertalingen op de site te zetten, dus het voelt voor ons een beetje als overkill. Mochten we naast het developmentwerk nog tijd hebben om met bijvoorbeeld Github Actions aan de slag te gaan (en daar tegen die tijd nog doorslaggevend voordeel uit denken te halen), zullen we zeker een blik op werpen!
