### ISSUE TITLE
Vimeo als streaming bron? Uitzoeken

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#78]
Can we use Vimeo as a streaming source? See accessibility issue requirements at #60

https://vimeo.com/upgrade

**Comment by alexdekok** [comment]
Ha Edo, waar we rekening mee moeten houden is dat we Rijksvideo als volgt moeten aanbieden:

- Video voor "normale mensen zonder enige problemen"
- Video voor mensen die meer contrast nodig hebben
- Video met ondertiteling
- Los uitgeschreven teksten voor mensen met een screenreader
---> Zie hiervoor de andere cards die gaan over het aanbieden van video's.


https://vimeo.com/blog/post/accessibility-updates-to-the-vimeo-player/ schrijft Vimeo hierover.

Ik twijfel alleen of wat zij schrijven alleen maar gaat over de elementen van hun player en niet over zaken als uitgeschreven teksten die toegankelijk zijn voor elke gebruiker. Ik heb hier ook een vraag over uitstaan bij een partij die Rijksvideo's toegankelijk maakt.

**Comment by EdoPlantinga** [comment]
Good catch! Ze claimen zelf niveau AA te halen (het gewenste niveau volgens digitoegankelijk), dus neem aan dat uitgeschreven teksten hier ook onder vallen. We kunnen Bram consulteren hierover. 
@MartinW-com pak jij deze verder op?

**Comment by mellewynia** [comment]
Dit ticket is inmiddels outdated. We hebben een eigen mediaplayer en video hosten we zelf.
