### ISSUE TITLE
Add (generated?) og:image

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-website#8]
So add to [`_includes/head.html`](https://github.com/minvws/nl-covid19-notification-app-dashboard/blob/master/_includes/head.html):
```html
<meta name="og:image" content="...">
<meta name="twitter:card" content="summary_large_image">
```

Main ingredient missing: an image, preferably auto generated with some :vertical_traffic_light:'s displaying the status of features.

**Comment by EdoPlantinga** [comment]
@bwbroersma This one seems outdated. I closed it.

**Comment by bwbroersma** [comment]
Yes & no. There should be open graph metadata, including an `og:image`, maybe not auto generated, but currently there is none.
