### ISSUE TITLE
Security headers

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#80]
Daarnaast is het sterk aan te raden óók alle Securityheaders die Internet.nl noemt goed te implementeren, inclusief een goede Content Security Policy en de Privacy Policy (heet inmiddels ‘Permissions Header’, zie https://w3c.github.io/webappsec-feature-policy/), zie ook https://securityheaders.com/

**Comment by tomwassenberg** [comment]
In de HSTS-header op https://coronamelder.nl wordt momenteel het `preload`-attribuut gebruikt, maar dit wordt niet erkend zonder ook `includeSubDomains` te gebruiken. Daarnaast moet de `max-age` op min. één jaar gezet worden, i.p.v. zes maanden.

Dit zijn beide eisen die door Chrome gesteld worden om daadwerkelijk gepreload te kunnen worden, zoals [hier](https://hstspreload.org/?domain=coronamelder.nl) te zien en te verifiëren is.

**Comment by mellewynia** [comment]
Bedankt voor de tip, @tomwassenberg ! Dit neem ik mee.

**Comment by NL-William** [comment]
Check ook de tips op https://observatory.mozilla.org/analyze/coronamelder.nl.

Samengevat komt dat neer op:
 * referer header zetten (advies: strict-origin-when-cross-origin)
 * CSP met base setting, frame-ancestors (gelijke setting als x-frame-options) en form-actions parameters.

Tevens is het verstandig nog aandacht te geven aan:
 * CSP reporting inschakelen, zodat misbruik (XSS) naast dat het gestopt wordt door CSP ook gedetecteerd wordt.
 * Ook een Feature policy (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy) kan goed zijn om te zetten (eg. verbieden dat de site de camera aanzet, zelfs als iemand ooit een script erin krijgt die dat probeert).

**Comment by NL-William** [comment]
Mocht het DNS beheer ook in handen zijn (gaat net iets verder dan een header, maar past goed in het lijstje :)): zet vooral ook in DNS 'CAA', zodat niemand certificaten kan uitgeven behalve PKI Overheid zelf.

Meer info: https://blog.qualys.com/ssllabs/2017/03/13/caa-mandated-by-cabrowser-forum?

**Comment by gberkouwer** [comment]
tomwassenberg: > In de HSTS-header op https://coronamelder.nl wordt momenteel het preload-attribuut gebruikt, maar dit wordt niet erkend zonder ook includeSubDomains te gebruiken. Daarnaast moet de max-age op min. één jaar gezet worden, i.p.v. zes maanden.
> Bedankt voor de tip, @tomwassenberg ! Dit neem ik mee.

En als dat goed staat zul je het domein ook nog wel moeten aanmelden op https://hstspreload.org/

**Comment by bwbroersma** [comment]
Ik wilde net deze issue melden na het lezen van [de pentest](https://www.rijksoverheid.nl/onderwerpen/coronavirus-app/documenten/rapporten/2020/07/15/testrapport-penetratietest-coronamelder) waar ik de HSTS in zag met te lage `max-age` en zonder `includeSubDomains`, gek genoeg zeuren ze daar wel over dubbele `Cache-Control` header (in spec, bij welke software is dit een issue dan?) maar niet over deze :joy:.
