### ISSUE TITLE
Deeplinken naar popups

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#81]
De uitleg van de vragen gaan met pop up schermen. Betekent dit dat er geen unieke url is per vraag/uitlegpagina? Hoe zit het dan met de vindbaarheid? En met de communicatie van eventueel losse pagina’s onder de aandacht brengen op bijvoorbeeld social?

**Comment by erikkroes** [comment]
Daarnaast zijn deze zijwaartse modals niet goed opgebouwd in de html code, en zijn ze erg onhandig voor mensen die inzoomen op pagina's eerder het linker- of middendeel in de gaten houden. Het verwijderen van pop-ups is een hele praktische oplossing die de website simpeler maakt en ook nog eens flink wat ontwikkeltijd scheelt.

**Comment by EdoPlantinga** [comment]
@mellewynia Kun je hier iets mee? Merk op dat het deeplinken na livegang mag worden toegevoegd wmb. 
@erikkroes hartelijk dank voor de review?

**Comment by anneke** [comment]
We hebben de feedback op dit punt verwerkt in het nieuwe design, en op de website komen geen horizontale modals meer voor. Elke vraag linkt nu door naar een aparte pagina. Daarmee sluit ik deze issue!
