### ISSUE TITLE
Feedback content 

### ISSUE THREAD

**Issue by alexdekok** [minvws/nl-covid19-notification-app-website#84]
### Describe the bug, issue or concern

- De tekst onder Wat det de App wordt nog aangepast. --> Hier volgt copy voor
-  Nadat je in de buurt bent geweest wijzigen in als je in de buurt bent geweest  Ceck svp dat we hier de juiste content gebruiken. Die ook in de onboarding van de app zit.
- FAQ de zin Er zullen de komende tijd aanpassen in: Er komen meer vragen en antwoorden beschikbaar
- Socials mogen eruit en hetzelfde geldt voor RIVM, VWS en GGD-logo.
-  Heading volgt een terugkoppeling op.
- Alleen Samen kunnen we ervoor zorgen dat  hier volgt een andere tekst voor.

**Comment by arianvp** [comment]
> De app werkt:
> zonder persoonsgegevens of locatiegegevens,
> met anonieme, willekeurige codes.

Dit zou (naar mijn mening) anders verwoord moeten worden. Zeggen dat de app geen persoonsgegevens verwerkt heeft een juridische betekenis, waarvan het niet duidelijk is of hij klopt. De app verwerkt gegevens, en met enige moeite is deze herleidbaar tot de persoon.  De crux is dat deze gegevens niet centraal verwerkt worden en dat er gewerkt wordt met pseudoniemen. 

Ik heb echter geen betere suggestie. Ik gooi een balletje op in de Slack

**Comment by arianvp** [comment]
Link naar de Slack-discussie  https://app.slack.com/client/T68FXPFQV/C011R4NCFMJ/thread/C011R4NCFMJ-1594113891.373900


Mijn persoonlijke samenvatting (a.dh.v. https://www.viacryp.nl/2018/08/27/wat-is-het-verschil-tussen-anonimiseren-en-pseudonimiseren/)

> ah ja goed artikel. Precies mijn punt maar dan beter verwoord.   Het is niet in our interest om te zeggen "De app is anoniem. De app verwerkt geen persoonsgegevens" (wat nu zo op de WIP website staat)   want dat wekt de illusie dat mensen niet beschermd worden door de AVG.     Je kunt beter beschrijven wat je wel en niet verzamelt, en juist benadrukken dat de AVG van toepassing is en de gebruiker beschermtIk val persoonlijk iets minder hard over het woord "anoniem" maar voornamelijk om in combinatie met het huidige zinnetje "de app verwerkt geen persoonsgegevens" (edited) 


Zie ook https://www.immuni.italia.it/faq.html en https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-englisch/corona-warn-app-faq-1758636  als FAQ-voorbeelden

**Comment by alexdekok** [comment]
@mellewynia zie 2 mails over de content van vanavond.
