### ISSUE TITLE
WCAG / digitoegankelijk test

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#87]
Corresponds to requirement 1 in [readme](https://github.com/minvws/nl-covid19-notification-app-website/blob/master/README.md#features-requirements-and-standards)

## Definition of done
- [x] Site is tested conforming to WCAG-EG (see https://www.digitoegankelijk.nl/aanpak/toegankelijkheidsonderzoek- )

**Comment by EdoPlantinga** [comment]
@anneke this still needs to be done, via an independent party. Re-opening the issue.

**Comment by anneke** [comment]
@EdoPlantinga I think this is a duplicate of (or already covered by) #88

**Comment by EdoPlantinga** [comment]
No, automated tests are not sufficient to test for WCAG accessibility, and apart from that we need to prove WCAG conformity by an external auditor.

**Comment by anneke** [comment]
(Ik maak een nieuwe issue op basis van de videospeler-toegankelijkheidsissues, waar @mellewynia nog aan gewerkt heeft)
