### ISSUE TITLE
Continuous accessibility tests

### ISSUE THREAD

**Issue by bramd** [minvws/nl-covid19-notification-app-website#88]
It would be nice if we could integrate accessibility tests in our continuous integration:

1. We could run Axe as paart of the build process
1. We could try the Axe linter for Github app to get immediate feedback on PRs: https://github.com/marketplace/axe-linter/

**Comment by jsoeterbroek** [comment]
See #73

**Comment by bramd** [comment]
FYI, I started work on this in the [axe-ci branch of my fork](https://github.com/bramd/nl-covid19-notification-app-website/tree/feature/axe-ci), but have no time to finish this right now. Feel free to use this branch and improve it.

**Comment by anneke** [comment]
Hoi, we hebben besloten om dit niet meer te implementeren gezien de gelimiteerde scope van het project.
