### ISSUE TITLE
FAQ website (na testen) categorie vs geen categorie

### ISSUE THREAD

**Issue by alexdekok** [minvws/nl-covid19-notification-app-website#89]
### Betreffende de werking van de veelgestelde vragen

- Gebruiker N=1 (ikzelf) had wat moeite met de veelgestelde vragen oplossing in categorieënc (gisteren ook via screenshare met Melle gedeeld). Ik snap dat er categorieën zijn, echter heb ik 2 ouderen even laten meekijken en die snapten niet het verschil tussen algemeen en werking van de app. Men snapte niet dat er je kunt klikken op de categorie. Hun eerste reactie was 'huh, zijn er maar 2 veelgestelde vragen'. Zou je niet veel meer de opbouw hebben als een opsomming van de belangrijkste bovenin en daaronder de overige vragen. Dus Algemeen en werking bundelen en bij de FAQ dus niet werken in een categorie. In feite zijn de menu's toch al een categorie van de meest belangrijke vragen en antwoorden? Daar is het overigens direct duidelijk bij de 2 personen die ik heb laten meekijken.
<img width="1552" alt="Schermafbeelding 2020-07-08 om 13 33 29" src="https://user-images.githubusercontent.com/67582540/86913902-a5524280-c11f-11ea-95c8-9f7331faf1a1.png">

**Comment by anneke** [comment]
Hoi Alex, de veelgestelde vragen zijn nu zo veranderd, dat deze issue volgens mij gesloten kan worden!
