### ISSUE TITLE
Social share image

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-website#92]

**Comment by mellewynia** [comment]
Meta tags toegevoegd in header. Content (incl. image) kan worden aangepast als content.

Hier een impressie van de stand-van-zaken tijdens schrijven:

<img width="971" alt="Screenshot 2020-07-09 at 11 18 54" src="https://user-images.githubusercontent.com/635312/87022441-ca55bc80-c1d6-11ea-9096-02116aff4952.png">

<img width="506" alt="Schermafbeelding 2020-07-09 om 11 19 57" src="https://user-images.githubusercontent.com/635312/87022518-dfcae680-c1d6-11ea-97d4-de58a8016b85.png">
