### ISSUE TITLE
Kwetsbaarheid melden in footer

### ISSUE THREAD

**Issue by alexdekok** [minvws/nl-covid19-notification-app-website#93]
### Copy toevoegen in footer:

Ontdekt u een zwakke plek of kwetsbaarheid op deze website, meld dit dan aan het Nationaal Cyber Security Centrum (NCSC). Het maken van zo'n melding heet Coordinated Vulnerability Disclosure (CVD).

Wij bekijken samen met het NCSC het probleem en lossen dit zo snel mogelijk op.

<buttonnaam meld kwetsbaarheid>https://www.ncsc.nl/contact/kwetsbaarheid-melden<buttonnaam meld kwetsbaarheid>

Luc checkt final of dit klopt

**Comment by erikkroes** [comment]
Waarom specifiek "kwetsbaarheden" en niet tekortkomingen in algemenere zin?
