### ISSUE TITLE
Font-gebruik

### ISSUE THREAD

**Issue by alexdekok** [minvws/nl-covid19-notification-app-website#97]
Eerder al aangegeven dat we goed moeten checken op de Rijksoverheidstijl om te gebruiken. Er werd positief op gereageerd, echter lijkt er een kleine onzuiverheid in geslopen te zijn. Het font wat nu wordt gebruikt komt niet overeen met de fonts die er gebruikt mogen worden rondom Rijksoverheid websites.

Zie https://www.rijkshuisstijl.nl/basiselementen/basiselementen-online/webfonts.
  
E.g. 

Graag bij weinig impact direct oppakken, anders als high prio voor de volgende release

**Comment by EdoPlantinga** [comment]
@alexdekok vind deze persoonlijk minder belangrijk, geen blocker voor livegang wmb. De app zelf is ook niet in het rijkshuisstijl font, daar worden native fonts gebruikt. Wmb hi prio na livegang prima. 
@MartinW-com my 2 cents, beslis jij maar
